In [1]:
############################################################################
# nn.Linear example 
############################################################################

In [2]:
# https://pytorch.org/docs/stable/generated/torch.nn.Linear.html

In [3]:
#######################################
# (1, ) tensor -> (1, ) tensor
#######################################

In [4]:
import torch
import torch.nn as nn

in_features = 1
out_features = 1
linear = nn.Linear(in_features, out_features) 
linear

Linear(in_features=1, out_features=1, bias=True)

In [5]:
linear.state_dict() # weight is initialized at random

OrderedDict([('weight', tensor([[-0.8025]])), ('bias', tensor([0.9904]))])

In [6]:
linear.state_dict()['weight']

tensor([[-0.8025]])

In [7]:
linear.state_dict()['bias'] 

tensor([0.9904])

In [8]:
# edit the parameters of linear for simplicity

new_weight = torch.tensor([[2.0]])
new_bias = torch.tensor([0.0])

linear.weight.data = new_weight
linear.bias.data = new_bias

linear.state_dict()

OrderedDict([('weight', tensor([[2.]])), ('bias', tensor([0.]))])

In [9]:
# 1 sample

x = torch.tensor([[2.0]]) # TensorFloat32
output = linear(x) # linear supports TensorFloat32.
output 

tensor([[4.]], grad_fn=<AddmmBackward0>)

In [10]:
output.dtype

torch.float32

In [11]:
# linear(x) = x @ weight.T + bias

weight = linear.state_dict()['weight']
bias = linear.state_dict()['bias']
x @ weight.T + bias # equal to linear(x) 

tensor([[4.]])

In [12]:
# linear does not support int

x = torch.tensor([1]) # torch.int64
try:
    output = linear(x)
except RuntimeError as e:
    print(e)

expected scalar type Long but found Float


In [13]:
# 10 sample

X = torch.rand(10, 1)
X

tensor([[0.1612],
        [0.2901],
        [0.4052],
        [0.2523],
        [0.4594],
        [0.0514],
        [0.0932],
        [0.7344],
        [0.2791],
        [0.2425]])

In [14]:
linear(X)

tensor([[0.3224],
        [0.5802],
        [0.8105],
        [0.5046],
        [0.9187],
        [0.1028],
        [0.1864],
        [1.4688],
        [0.5582],
        [0.4850]], grad_fn=<AddmmBackward0>)

In [15]:
#######################################
# (3, ) tensor -> (2, ) tensor
#######################################

In [16]:
import torch
import torch.nn as nn

in_features = 3
out_features = 2
linear = nn.Linear(in_features, out_features) 
linear

Linear(in_features=3, out_features=2, bias=True)

In [17]:
linear.state_dict()

OrderedDict([('weight',
              tensor([[-0.3109, -0.4281, -0.3381],
                      [ 0.2274, -0.0970, -0.2259]])),
             ('bias', tensor([-0.5284, -0.3925]))])

In [18]:
# 1 sample

x = torch.tensor([[1.0, 2.0, 3.0]])
linear(x)

tensor([[-2.7097, -1.0368]], grad_fn=<AddmmBackward0>)

In [19]:
# linear(x) = x @ weight.T + bias

weight = linear.state_dict()['weight']
bias = linear.state_dict()['bias']

x @ weight.T + bias

tensor([[-2.7097, -1.0368]])

In [20]:
# 10 sample

X = torch.rand(10, 3)
X

tensor([[0.8988, 0.2372, 0.1311],
        [0.5611, 0.0958, 0.7268],
        [0.0871, 0.9591, 0.0419],
        [0.3710, 0.2652, 0.9253],
        [0.4308, 0.3679, 0.3419],
        [0.7479, 0.4343, 0.7789],
        [0.0140, 0.0134, 0.3432],
        [0.6218, 0.0946, 0.4505],
        [0.6328, 0.3102, 0.8661],
        [0.3189, 0.1571, 0.5591]])

In [21]:
linear(X)

tensor([[-0.9537, -0.2407],
        [-0.9896, -0.4383],
        [-0.9803, -0.4752],
        [-1.0702, -0.5428],
        [-0.9355, -0.4074],
        [-1.2102, -0.4404],
        [-0.6546, -0.4681],
        [-0.9146, -0.3620],
        [-1.1508, -0.4743],
        [-0.8838, -0.4615]], grad_fn=<AddmmBackward0>)

In [22]:
# linear(X) = X @ weight.T + bias

X @ weight.T + bias

tensor([[-0.9537, -0.2407],
        [-0.9896, -0.4383],
        [-0.9803, -0.4752],
        [-1.0702, -0.5428],
        [-0.9355, -0.4074],
        [-1.2102, -0.4404],
        [-0.6546, -0.4681],
        [-0.9146, -0.3620],
        [-1.1508, -0.4743],
        [-0.8838, -0.4615]])