In [24]:
import numpy as np
from scipy.special import logsumexp

In [25]:
####################################
# logsumexp's input : 1d array
#===================================

In [26]:
x = np.array([-1000, -2000, -3000])

In [27]:
logsumexp(x) # logsumexp prevents underflow

-1000.0

In [28]:
sumexp = np.exp(x).sum() # underflow
sumexp

0.0

In [29]:
y = np.log(sumexp) # zero division warning

C:\Users\t0\AppData\Local\Temp\ipykernel_8036\4055062826.py:1: RuntimeWarning: divide by zero encountered in log
  y = np.log(sumexp) # zero division warning


In [30]:
# instead, calculate y = xmax + log(sum(exp(new_x)))
xmax=x.max() # -1000
new_x = x - xmax
new_x

array([    0, -1000, -2000])

In [31]:
sumexp= np.exp(new_x).sum() 
y = xmax + np.log(sumexp) 
y

-1000.0

In [32]:
error = y - logsumexp(x)
error

0.0

In [33]:
####################################
# logsumexp's input: 2d-array
#===================================

In [34]:
import numpy as np
from scipy.special import logsumexp

In [35]:
X = np.array([[-1000, -2000, -3000], [-2000, -2500, -3000], [-50, -40, -1000], [-100, -500, -400]])

In [36]:
X

array([[-1000, -2000, -3000],
       [-2000, -2500, -3000],
       [  -50,   -40, -1000],
       [ -100,  -500,  -400]])

In [37]:
# logsumexp
logsumexp(X, axis=1)

array([-1000.       , -2000.       ,   -39.9999546,  -100.       ])

In [38]:
# do the same thing with 2d numpy array

In [39]:
Xmax = X.max(axis=1)

In [40]:
Xmax

array([-1000, -2000,   -40,  -100])

In [41]:
Xmax[..., np.newaxis]

array([[-1000],
       [-2000],
       [  -40],
       [ -100]])

In [42]:
new_X = X - Xmax[..., np.newaxis]
new_X

array([[    0, -1000, -2000],
       [    0,  -500, -1000],
       [  -10,     0,  -960],
       [    0,  -400,  -300]])

In [43]:
sumexps = np.exp(new_X).sum(axis=1)
sumexps

array([1.       , 1.       , 1.0000454, 1.       ])

In [44]:
Y = Xmax + np.log(sumexps)
Y

array([-1000.       , -2000.       ,   -39.9999546,  -100.       ])

In [45]:
errors = (Y - logsumexp(X, axis=1))**2
errors

array([0., 0., 0., 0.])