In [1]:
import numpy as np

In [2]:
##########################################################################
# choose values from a list of strings by specifying its indices
#=========================================================================

In [3]:
# choices is a list of strings
index_array = [0,0,0,1,2,0,0] # array indices(=first axis) I'm going to choose
choices = ["win", "draw", "lose"]
np.choose(index_array,choices)

array(['win', 'win', 'win', 'draw', 'lose', 'win', 'win'], dtype='<U4')

In [4]:
##########################################################################
# choose values from a 2D array of integers 
#=========================================================================

In [5]:
# choices is a 2D array of integers
array2d = lambda m, n: [[i*10+j for j in range(n)] for i in range(m)]
choices = array2d(7, 3)
choices

[[0, 1, 2],
 [10, 11, 12],
 [20, 21, 22],
 [30, 31, 32],
 [40, 41, 42],
 [50, 51, 52],
 [60, 61, 62]]

In [6]:
# choose row by specifying its index
np.choose(3, choices) 

array([30, 31, 32])

In [7]:
# choose choices[i0][0], ..., choices[i2][2] where i_n are in index_array
index_array = [0, 0, 5] 
np.choose(index_array, choices) # 1d array whose length is 3

array([ 0,  1, 52])

In [8]:
# choose choices[i0][0], ..., choices[i2][2] where i_n are in index_array
index_array = [0, 2, 4] 
np.choose(index_array, choices) # 1d array whose length is 3

array([ 0, 21, 42])

In [9]:
##########################################################################
# choose values from a 3D array of integers 
#=========================================================================

In [10]:
array3d = lambda m, n, l: [[[100*i+10*j+k for k in range(l)] for j in range(n)] for i in range(m)]
choices = np.array(array3d(5, 3, 4))
choices

array([[[  0,   1,   2,   3],
        [ 10,  11,  12,  13],
        [ 20,  21,  22,  23]],

       [[100, 101, 102, 103],
        [110, 111, 112, 113],
        [120, 121, 122, 123]],

       [[200, 201, 202, 203],
        [210, 211, 212, 213],
        [220, 221, 222, 223]],

       [[300, 301, 302, 303],
        [310, 311, 312, 313],
        [320, 321, 322, 323]],

       [[400, 401, 402, 403],
        [410, 411, 412, 413],
        [420, 421, 422, 423]]])

In [11]:
# choose choices[0]
np.choose(0, choices)

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [12]:
# choose choices[i0][0],..., choices[i3][3], where i_n are in index_array 
index_array = np.array([0, 0, 1, 2]) # this shape is choices.shape[2:]
np.choose(index_array, choices) 

array([[  0,   1, 102, 203],
       [ 10,  11, 112, 213],
       [ 20,  21, 122, 223]])

In [13]:
# choose choices[i0][0,0],choices[i1][0,1],..., choices[i11][2,3], where i_n are in index_array 
index_array = np.array([[0, 0, 1, 2], [2, 2, 1,1], [1,2,0,0]]) # this shape is choices.shape[1:]
np.choose(index_array, choices) 

array([[  0,   1, 102, 203],
       [210, 211, 112, 113],
       [120, 221,  22,  23]])