# diagonalization example

$$A = \begin{bmatrix}
2 & 1 \\
1 & 2 \\
\end{bmatrix}
$$

is diagonalized as:

$$D = P^T A P = \begin{bmatrix}
3 & 0 \\
0 & 1 \\
\end{bmatrix}$$

* https://en.wikipedia.org/wiki/Diagonalizable_matrix

In [1]:
import numpy as np
import matplotlib.pyplot as plt

A = np.array([[2, 1], 
              [1, 2]])

eigenvalues, P = np.linalg.eig(A)
eigenvalues, P 

(array([3., 1.]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [2]:
P.T @ A @ P

array([[3., 0.],
       [0., 1.]])

A is diagonalizable, because P[:,0] and P[:, 1] are linearly independent.

# is_diagonalizable function

A is diagonalizable $\Leftrightarrow$ eigenvectors of $A$ are linearly independent


In [3]:
import numpy as np

def is_diagonalizable(A):
    # Compute the eigenvalues and eigenvectors
    eigenvalues, eigenvectors = np.linalg.eig(A)

    # Check if there are enough linearly independent eigenvectors
    return np.all(np.linalg.matrix_rank(eigenvectors) == eigenvectors.shape[1])


In [4]:
# Define your matrix A
A = np.array([[1, 1],
              [0, 1]])

is_diagonalizable(A)

False

In [5]:
eigenvalues, eigenvectors = np.linalg.eig(A)
np.round(eigenvalues, decimals=8), np.round(eigenvectors, decimals=8)

(array([1., 1.]),
 array([[ 1., -1.],
        [ 0.,  0.]]))

# A real-valued symmetric matrix is diagonalizable

In [6]:
def get_symmetric_array(dim=3):
    A = np.random.choice(5, (3,3))
    A = A + A.T
    return A
    
A = get_symmetric_array()
print(A)

eigenvalues, P = np.linalg.eig(A)
eigenvalues, P 

[[2 7 2]
 [7 8 3]
 [2 3 2]]


(array([13.72453292, -2.61586123,  0.89132832]),
 array([[ 0.52644687,  0.83546142, -0.15766393],
        [ 0.79778219, -0.54952779, -0.24811847],
        [ 0.29393412, -0.00483972,  0.95581343]]))

In [7]:
np.round(P.T @ A @ P, decimals=8) 

array([[13.72453292, -0.        ,  0.        ],
       [-0.        , -2.61586123,  0.        ],
       [-0.        , -0.        ,  0.89132832]])

# Handling Repeated Eigenvalues


The matrix A:

$$
A = \begin{bmatrix}
0 & 1 & 1 \\
1 & 0 & 1 \\
1 & 1 & 0 \\
\end{bmatrix}
$$

Since A is a real-valued symmetric matrix, it can be diagonalized using an orthogonal matrix.


However, it's important to note that `np.linalg.eig` does not always return an orthogonal matrix as eigenvectors when there are repeated eigenvalues. In such cases, you should use the inverse of P instead.

The diagonalization equation is:

$$
P^{-1} A P = D
$$

Where:
- A is the original matrix.
- P is the matrix containing the eigenvectors as columns.
- D is a diagonal matrix with the eigenvalues on the diagonal.


In [8]:
A = np.array([[0,1,1],
              [1,0,1],
              [1,1,0]])
lams, P = np.linalg.eig(A)
lams, P

(array([-1.,  2., -1.]),
 array([[-0.81649658,  0.57735027, -0.09265789],
        [ 0.40824829,  0.57735027, -0.65620994],
        [ 0.40824829,  0.57735027,  0.74886783]]))

In [9]:
is_diagonalizable(A)

True

In [10]:
P.T @ P # P is not orthogonal

array([[ 1.00000000e+00, -1.11022302e-16,  1.13482280e-01],
       [-1.11022302e-16,  1.00000000e+00,  1.66533454e-16],
       [ 1.13482280e-01,  1.66533454e-16,  1.00000000e+00]])

In [11]:
P_inv = np.linalg.inv(P) # instead, use the inverse of P
D = P_inv @ A@ P # diagonalizable
np.round(D, decimals=8)

array([[-1.,  0.,  0.],
       [ 0.,  2.,  0.],
       [ 0., -0., -1.]])