# doubly stochastic matrix P

https://en.wikipedia.org/wiki/Doubly_stochastic_matrix

$$
P = 
\begin{bmatrix}
p_{11} & p_{12} & \dots & p_{1N} \\
p_{21} & p_{22} & \dots & p_{2N} \\
\vdots & \vdots & \ddots & \vdots \\
p_{N1} & p_{N2} & \dots & p_{NN} \\
\end{bmatrix}
$$

## P.sum(axis=0) == [1,1,...,1]
$$ \sum_{i=1}^N p_{ij} = 1 (j=1,2,...,N)$$

## P.sum(axis=1) == [1,1,...,1]
$$\sum_{j=1}^N p_{ij} = 1 (i=1,2,...,N)$$



# generate a doubly stochastic

In [1]:
import numpy as np

N=4
matrix = np.random.random([N, N])
matrix

array([[0.42335298, 0.11982681, 0.21468947, 0.47908566],
       [0.00592135, 0.99989255, 0.17164664, 0.98658758],
       [0.10503041, 0.55715725, 0.4591049 , 0.08286042],
       [0.13891288, 0.40933452, 0.03840619, 0.45968149]])

In [2]:
MAX_ITER = 100
epsilon = 1e-32

for i in range(MAX_ITER):
    matrix /= np.sum(matrix, axis=0)
    matrix /= np.sum(matrix, axis=1)[:, np.newaxis]
    
    row_losses = (matrix.sum(axis=1) - 1)**2
    col_losses = (matrix.sum(axis=0) - 1)**2
    
    total_loss = row_losses.sum() + col_losses.sum()
    
    if total_loss < epsilon:
        break

matrix  # Doubly stochastic matrix

array([[0.53261734, 0.04818101, 0.2167083 , 0.20249336],
       [0.00745144, 0.40214478, 0.17330349, 0.41710028],
       [0.15461809, 0.26213933, 0.54226208, 0.0409805 ],
       [0.30531313, 0.28753488, 0.06772613, 0.33942586]])

In [3]:
matrix.sum(axis=0)

array([1., 1., 1., 1.])

In [4]:
matrix.sum(axis=1)

array([1., 1., 1., 1.])

In [5]:
(matrix @ matrix).sum(axis=0)

array([1., 1., 1., 1.])

In [6]:
(matrix @ matrix).sum(axis=1)

array([1., 1., 1., 1.])

# lim P^n  
Let P be an NxN doubly stochastic matrix, then

$$ P^n \rightarrow 
\begin{bmatrix}
\frac{1}{N} & \frac{1}{N} & \dots & \frac{1}{N} \\
\frac{1}{N} & \frac{1}{N} & \dots & \frac{1}{N} \\
\vdots & \vdots & \ddots & \vdots \\
\frac{1}{N} & \frac{1}{N} & \dots & \frac{1}{N} \\
\end{bmatrix}  (n\rightarrow +\infty)
$$

In [7]:
def generate_doubly_stochastic_matrix(N:int):
    matrix = np.random.random([N, N])
    MAX_ITER = 100
    epsilon = 1e-16

    for i in range(MAX_ITER):
        matrix /= np.sum(matrix, axis=0)
        matrix /= np.sum(matrix, axis=1)[:, np.newaxis]

        row_losses = (matrix.sum(axis=1) - 1)**2
        col_losses = (matrix.sum(axis=0) - 1)**2

        total_loss = row_losses.sum() + col_losses.sum()

        if total_loss < epsilon:
            return matrix
    return None


def is_doubly_stochastic(matrix: np.ndarray):
    # Check if the input is np.ndarray
    if not isinstance(matrix, np.ndarray):
        return False
    
    # Check if the matrix is square
    n = matrix.shape[0]
    if matrix.shape[0] != matrix.shape[1]:
        return False

    # Check if each row sums up to 1
    row_sums = np.sum(matrix, axis=1)
    if not np.allclose(row_sums, np.ones(n)):
        return False

    # Check if each column sums up to 1
    column_sums = np.sum(matrix, axis=0)
    if not np.allclose(column_sums, np.ones(n)):
        return False

    return True

# Compute P^n
def compute_power_doubly_stochastic_matrix(P: np.ndarray, n:int):
    result = P
    for _ in range(n):
        result = result @ P
    return result

# lim P^n (N=2)

In [8]:
N = 2
P = generate_doubly_stochastic_matrix(N)
P

array([[0.40985148, 0.59014852],
       [0.59014852, 0.40985148]])

In [9]:
is_doubly_stochastic(P)

True

In [10]:
Q = compute_power_doubly_stochastic_matrix(P, 100)
Q

array([[0.5, 0.5],
       [0.5, 0.5]])

# lim P^n (N=4)

In [11]:
N = 4
P = generate_doubly_stochastic_matrix(N)
P

array([[0.26824436, 0.07619656, 0.25063231, 0.40492677],
       [0.00586189, 0.45682875, 0.47002726, 0.06728209],
       [0.53553436, 0.11624239, 0.21939744, 0.12882582],
       [0.19035938, 0.35073231, 0.05994299, 0.39896532]])

In [12]:
is_doubly_stochastic(P)

True

In [13]:
Q = compute_power_doubly_stochastic_matrix(P, 100)
Q

array([[0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25]])