# doubly stochastic matrix P

https://en.wikipedia.org/wiki/Doubly_stochastic_matrix

$$
P = 
\begin{bmatrix}
p_{11} & p_{12} & \dots & p_{1N} \\
p_{21} & p_{22} & \dots & p_{2N} \\
\vdots & \vdots & \ddots & \vdots \\
p_{N1} & p_{N2} & \dots & p_{NN} \\
\end{bmatrix}
$$

## P.sum(axis=0) == [1,1,...,1]
$$ \sum_{i=1}^N p_{ij} = 1 (j=1,2,...,N)$$

## P.sum(axis=1) == [1,1,...,1]
$$\sum_{j=1}^N p_{ij} = 1 (i=1,2,...,N)$$



# generate a doubly stochastic

In [1]:
import numpy as np

N=4
matrix = np.random.random([N, N])
matrix

array([[0.89773877, 0.82386191, 0.10930065, 0.92425775],
       [0.33934369, 0.82292954, 0.36357303, 0.53842813],
       [0.11972913, 0.9754663 , 0.68466937, 0.77751695],
       [0.99444671, 0.71277582, 0.46979606, 0.07144255]])

In [2]:
MAX_ITER = 100
epsilon = 1e-32

for i in range(MAX_ITER):
    matrix /= np.sum(matrix, axis=0)
    matrix /= np.sum(matrix, axis=1)[:, np.newaxis]
    
    row_losses = (matrix.sum(axis=1) - 1)**2
    col_losses = (matrix.sum(axis=0) - 1)**2
    
    total_loss = row_losses.sum() + col_losses.sum()
    
    if total_loss < epsilon:
        break

matrix  # Doubly stochastic matrix

array([[0.34392222, 0.22319482, 0.06042434, 0.37245861],
       [0.16863366, 0.28919221, 0.26072046, 0.28145366],
       [0.04577817, 0.26374869, 0.37776216, 0.31271098],
       [0.44166594, 0.22386427, 0.30109304, 0.03337675]])

In [3]:
matrix.sum(axis=0)

array([1., 1., 1., 1.])

In [4]:
matrix.sum(axis=1)

array([1., 1., 1., 1.])

In [5]:
(matrix @ matrix).sum(axis=0)

array([1., 1., 1., 1.])

In [6]:
(matrix @ matrix).sum(axis=1)

array([1., 1., 1., 1.])

# lim P^n  
Let P be an NxN doubly stochastic matrix, then

$$ P^n \rightarrow 
\begin{bmatrix}
\frac{1}{N} & \frac{1}{N} & \dots & \frac{1}{N} \\
\frac{1}{N} & \frac{1}{N} & \dots & \frac{1}{N} \\
\vdots & \vdots & \ddots & \vdots \\
\frac{1}{N} & \frac{1}{N} & \dots & \frac{1}{N} \\
\end{bmatrix}  (n\rightarrow +\infty)
$$

In [7]:
def generate_doubly_stochastic_matrix(N:int):
    matrix = np.random.random([N, N])
    MAX_ITER = 100
    epsilon = 1e-16

    for i in range(MAX_ITER):
        matrix /= np.sum(matrix, axis=0)
        matrix /= np.sum(matrix, axis=1)[:, np.newaxis]

        row_losses = (matrix.sum(axis=1) - 1)**2
        col_losses = (matrix.sum(axis=0) - 1)**2

        total_loss = row_losses.sum() + col_losses.sum()

        if total_loss < epsilon:
            return matrix
    return None


def is_doubly_stochastic(matrix: np.ndarray):
    # Check if the input is np.ndarray
    if not isinstance(matrix, np.ndarray):
        return False
    
    # Check if the matrix is square
    n = matrix.shape[0]
    if matrix.shape[0] != matrix.shape[1]:
        return False

    # Check if each row sums up to 1
    row_sums = np.sum(matrix, axis=1)
    if not np.allclose(row_sums, np.ones(n)):
        return False

    # Check if each column sums up to 1
    column_sums = np.sum(matrix, axis=0)
    if not np.allclose(column_sums, np.ones(n)):
        return False

    return True

# Compute P^n
def compute_power_doubly_stochastic_matrix(P: np.ndarray, n:int):
    result = P
    for _ in range(n):
        result = result @ P
    return result

# lim P^n (N=2)

In [8]:
N = 2
P = generate_doubly_stochastic_matrix(N)
P

array([[0.26125484, 0.73874516],
       [0.73874516, 0.26125484]])

In [9]:
is_doubly_stochastic(P)

True

In [10]:
Q = compute_power_doubly_stochastic_matrix(P, 100)
Q

array([[0.5, 0.5],
       [0.5, 0.5]])

# lim P^n (N=4)

In [11]:
N = 5
P = generate_doubly_stochastic_matrix(N)
P

array([[0.12335103, 0.21860203, 0.26965177, 0.37770271, 0.01069247],
       [0.00364336, 0.30933198, 0.0999315 , 0.13933952, 0.44775364],
       [0.25222994, 0.09704091, 0.19365041, 0.22361849, 0.23346024],
       [0.32263109, 0.06177966, 0.28560053, 0.07008472, 0.25990399],
       [0.29814458, 0.31324542, 0.15116579, 0.18925456, 0.04818965]])

In [12]:
is_doubly_stochastic(P)

True

In [13]:
Q = compute_power_doubly_stochastic_matrix(P, 100)
Q

array([[0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2]])