# doubly stochastic matrix P

https://en.wikipedia.org/wiki/Doubly_stochastic_matrix

$$
P = 
\begin{bmatrix}
p_{11} & p_{12} & \dots & p_{1N} \\
p_{21} & p_{22} & \dots & p_{2N} \\
\vdots & \vdots & \ddots & \vdots \\
p_{N1} & p_{N2} & \dots & p_{NN} \\
\end{bmatrix}
$$

## P.sum(axis=0) == [1,1,...,1]
$$ \sum_{i=1}^N p_{ij} = 1 (j=1,2,...,N)$$

## P.sum(axis=1) == [1,1,...,1]
$$\sum_{j=1}^N p_{ij} = 1 (i=1,2,...,N)$$



# generate a doubly stochastic matrix

In [ ]:
import numpy as np

N=4
matrix = np.random.random([N, N])
matrix

In [2]:
MAX_ITER = 100
epsilon = 1e-32

for i in range(MAX_ITER):
    matrix /= np.sum(matrix, axis=0)
    matrix /= np.sum(matrix, axis=1)[:, np.newaxis]
    
    row_losses = (matrix.sum(axis=1) - 1)**2
    col_losses = (matrix.sum(axis=0) - 1)**2
    
    total_loss = row_losses.sum() + col_losses.sum()
    
    if total_loss < epsilon:
        break

matrix  # Doubly stochastic matrix

array([[0.37568095, 0.08975479, 0.15709251, 0.37747175],
       [0.32744026, 0.18492268, 0.27860026, 0.2090368 ],
       [0.24018244, 0.38674731, 0.24475737, 0.12831287],
       [0.05669634, 0.33857521, 0.31954986, 0.28517859]])

In [3]:
matrix.sum(axis=0)

array([1., 1., 1., 1.])

In [4]:
matrix.sum(axis=1)

array([1., 1., 1., 1.])

In [5]:
(matrix @ matrix).sum(axis=0)

array([1., 1., 1., 1.])

In [6]:
(matrix @ matrix).sum(axis=1)

array([1., 1., 1., 1.])

# lim P^n  
Let P be an NxN doubly stochastic matrix, then

$$ P^n \rightarrow 
\begin{bmatrix}
\frac{1}{N} & \frac{1}{N} & \dots & \frac{1}{N} \\
\frac{1}{N} & \frac{1}{N} & \dots & \frac{1}{N} \\
\vdots & \vdots & \ddots & \vdots \\
\frac{1}{N} & \frac{1}{N} & \dots & \frac{1}{N} \\
\end{bmatrix}  (n\rightarrow +\infty)
$$

In [7]:
def generate_doubly_stochastic_matrix(N:int):
    matrix = np.random.random([N, N])
    MAX_ITER = 100
    epsilon = 1e-16

    for i in range(MAX_ITER):
        matrix /= np.sum(matrix, axis=0)
        matrix /= np.sum(matrix, axis=1)[:, np.newaxis]

        row_losses = (matrix.sum(axis=1) - 1)**2
        col_losses = (matrix.sum(axis=0) - 1)**2

        total_loss = row_losses.sum() + col_losses.sum()

        if total_loss < epsilon:
            return matrix
    return matrix


def is_doubly_stochastic(matrix: np.ndarray):
    # Check if the input is np.ndarray
    if not isinstance(matrix, np.ndarray):
        return False
    
    # Check if the matrix is square
    n = matrix.shape[0]
    if matrix.shape[0] != matrix.shape[1]:
        return False

    # Check if each row sums up to 1
    row_sums = np.sum(matrix, axis=1)
    if not np.allclose(row_sums, np.ones(n)):
        return False

    # Check if each column sums up to 1
    column_sums = np.sum(matrix, axis=0)
    if not np.allclose(column_sums, np.ones(n)):
        return False

    return True

# Compute P^n
def compute_power_doubly_stochastic_matrix(P: np.ndarray, n:int):
    result = P
    for _ in range(n):
        result = result @ P
    return result

# lim P^n (N=2)

In [8]:
N = 2
P = generate_doubly_stochastic_matrix(N)
P

array([[0.17958258, 0.82041742],
       [0.82041743, 0.17958257]])

In [9]:
is_doubly_stochastic(P)

True

In [10]:
Q = compute_power_doubly_stochastic_matrix(P, 100)
Q

array([[0.5, 0.5],
       [0.5, 0.5]])

# lim P^n (N=4)

In [11]:
N = 4
P = generate_doubly_stochastic_matrix(N)
P

array([[0.27262112, 0.30928914, 0.00377336, 0.41431638],
       [0.31328513, 0.32616897, 0.33513873, 0.02540717],
       [0.24492803, 0.09885136, 0.28754007, 0.36868054],
       [0.16916572, 0.26569053, 0.37354784, 0.19159592]])

In [12]:
is_doubly_stochastic(P)

True

In [13]:
Q = compute_power_doubly_stochastic_matrix(P, 100)
Q

array([[0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25]])