## Kronecker Product

$$
A \otimes B
$$

https://en.wikipedia.org/wiki/Kronecker_product

In [1]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[0, 5], [6, 7]])

# Compute Kronecker products
kron_AB = np.kron(A, B)

print("\nA:")
print(A)
print("\nB:")
print(B)
print("\nkron(A,B):")
print(kron_AB)


A:
[[1 2]
 [3 4]]

B:
[[0 5]
 [6 7]]

kron(A,B):
[[ 0  5  0 10]
 [ 6  7 12 14]
 [ 0 15  0 20]
 [18 21 24 28]]


## Associative property
$$
(A \otimes B) \otimes C = A \otimes (B \otimes C)
$$

In [2]:
import numpy as np

m1, n1 = 2, 2
m2, n2 = 3, 2
m3, n3 = 1, 3
A = np.random.randint(1, 9, size=(m1,n1))
B = np.random.randint(1, 9, size=(m2,n2))
C = np.random.randint(1, 9, size=(m3,n3))

# Compute Kronecker products
kron_A_BC = np.kron(A, np.kron(B,C))
kron_AB_C = np.kron(np.kron(A, B), C)

if np.allclose(kron_A_BC, kron_AB_C):
    print("\nassociative property:")
    print("kron_A_BC == kron_AB_C")
else:
    print("something strange")
    

print("\nA:")
print(A)
print("\nB:")
print(B)
print("\nkron_A_BC:")
print(kron_A_BC)
print("\nkron_AB_C:")
print(kron_AB_C)


associative property:
kron_A_BC == kron_AB_C

A:
[[5 6]
 [2 3]]

B:
[[4 7]
 [7 6]
 [1 2]]

kron_A_BC:
[[ 40  40 120  70  70 210  48  48 144  84  84 252]
 [ 70  70 210  60  60 180  84  84 252  72  72 216]
 [ 10  10  30  20  20  60  12  12  36  24  24  72]
 [ 16  16  48  28  28  84  24  24  72  42  42 126]
 [ 28  28  84  24  24  72  42  42 126  36  36 108]
 [  4   4  12   8   8  24   6   6  18  12  12  36]]

kron_AB_C:
[[ 40  40 120  70  70 210  48  48 144  84  84 252]
 [ 70  70 210  60  60 180  84  84 252  72  72 216]
 [ 10  10  30  20  20  60  12  12  36  24  24  72]
 [ 16  16  48  28  28  84  24  24  72  42  42 126]
 [ 28  28  84  24  24  72  42  42 126  36  36 108]
 [  4   4  12   8   8  24   6   6  18  12  12  36]]


## eigenvalues
If  $\lambda$ is an eigenvalue of $A$  and  $\mu$ is an eigenvalue of $B$, then the eigenvalues of  $A \otimes B$ are $\lambda \mu$.


$$
\text{Eigenvalues of } A \otimes B: \quad \lambda_i \mu_j \quad \text{for } i, j,
$$

In [3]:
import numpy as np

m1, n1 = 2, 2 # must be square
m2, n2 = 3, 3 # must be square
A = np.random.randint(1, 9, size=(m1,n1))
B = np.random.randint(1, 9, size=(m2,n2))

# Compute Kronecker products
kron_AB = np.kron(A, B)

# Compute eigenvalues
eig_A, _ = np.linalg.eig(A)
eig_B, _ = np.linalg.eig(B)
eig_kron_AB, _ = np.linalg.eig(kron_AB)

# Compute eigenvalues of kron(A,B) using another formula
eig_kron_AB2 = np.array([l*m for l in eig_A for m in eig_B ])

# Compare two eigenvalues
eig_kron_AB.sort()
eig_kron_AB2.sort()

if np.allclose(eig_kron_AB, eig_kron_AB2):
    print("eigenvalues of kron(A,B) ==== eigenvalue of A * eigenvalue of B")
else:
    print("something strange")

# result
print("\nA:")
print(A)
print("\nB:")
print(B)
print("\neigenvalues of A:")
print(eig_A)
print("\neigenvalues of B:")
print(eig_B)
print("\neig_kron_AB:")
print(eig_kron_AB)
print("\neig_kron_AB2:")
print(eig_kron_AB2)

eigenvalues of kron(A,B) ==== eigenvalue of A * eigenvalue of B

A:
[[6 6]
 [7 3]]

B:
[[4 3 4]
 [1 8 3]
 [7 6 2]]

eigenvalues of A:
[11.15206735 -2.15206735]

eigenvalues of B:
[-2.79713382  4.33014031 12.46699351]

eig_kron_AB:
[-31.19382478 -26.82980967  -9.31875357   6.01962037  48.29001635
 139.03275129]

eig_kron_AB2:
[-31.19382478 -26.82980967  -9.31875357   6.01962037  48.29001635
 139.03275129]


## determinant

$$
\det(A \otimes B) = (\det A)^m (\det B)^n
$$

- A is an n×n matrix.
- B is an m×m matrix.


In [4]:
import numpy as np

# A, B must be non singular
m1, n1 = 2, 2 # must be square
m2, n2 = 3, 3 # must be square

A = np.random.randint(1, 9, size=(m1,n1))
B = np.random.randint(1, 9, size=(m2,n2))

# Compute kronecker product
kron_AB = np.kron(A, B)

# Compute determinants
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
det_kron_AB = np.linalg.det(kron_AB)

# Compute det(kron(A,B)) in other way
result = det_A ** m2 * det_B ** m1
is_equal = np.allclose(result, det_kron_AB)

if is_equal:
    print("\nDet(kron(A,B)) == [det(A)**size(B)] * [det(B)**size(A)]")
else:
    print("Something strange")

print("\nA:")
print(A)
print("\nB:")
print(B)
print("\nkron(A,B):")
print(kron_AB)
print("\ndet(kron(A,B))")
print(det_kron_AB)



Det(kron(A,B)) == [det(A)**size(B)] * [det(B)**size(A)]

A:
[[5 1]
 [4 6]]

B:
[[2 5 7]
 [3 3 2]
 [7 7 4]]

kron(A,B):
[[10 25 35  2  5  7]
 [15 15 10  3  3  2]
 [35 35 20  7  7  4]
 [ 8 20 28 12 30 42]
 [12 12  8 18 18 12]
 [28 28 16 42 42 24]]

det(kron(A,B))
632735.9999999976


## inverse
$$
(A \otimes B)^{-1} = A^{-1} \otimes B^{-1}
$$

In [5]:
import numpy as np

# A, B must be non singular
m1, n1 = 2, 2 # must be square
m2, n2 = 3, 3 # must be square

A = np.random.random(size=(m1,n1)) 
B = np.random.random(size=(m2,n2))

# Compute kronecker product
kron_AB = np.kron(A, B)

# Compute inverses
inv_A = np.linalg.inv(A)
inv_B = np.linalg.inv(B)
inv_kron_AB = np.linalg.inv(kron_AB)

# Compute equivalent formula
inv_kron_AB_equivalent = np.kron(inv_A, inv_B)

# Compare two equivalent formulas
is_equal = np.allclose(inv_kron_AB, inv_kron_AB_equivalent)

if is_equal:
    print("\ninv(kron(A,B)) ==== kron(inv(A), inv(B))")
else:
    print("Something strange")


print("\nA:")
print(A)
print("\nB:")
print(B)
print("\nkron(A,B):")
print(kron_AB)
print("\ninv(A):")
print(inv_A)
print("\ninv(B):")
print(inv_B)
print("\ninv(kron(A,B)):")
print(inv_kron_AB)




inv(kron(A,B)) ==== kron(inv(A), inv(B))

A:
[[0.85635689 0.88042816]
 [0.69346344 0.43483956]]

B:
[[0.86783086 0.04970484 0.54197302]
 [0.25808675 0.30936629 0.21684592]
 [0.5298746  0.99650316 0.98031895]]

kron(A,B):
[[0.74317294 0.04256508 0.46412233 0.76406273 0.04376154 0.47716831]
 [0.22101437 0.26492795 0.1856975  0.22722684 0.27237479 0.19091725]
 [0.45376176 0.85336234 0.83950289 0.46651652 0.87734944 0.86310041]
 [0.60180897 0.03446849 0.37583847 0.37736719 0.02161363 0.23567131]
 [0.17897373 0.21453421 0.15037472 0.11222633 0.1345247  0.09429318]
 [0.36744866 0.69103851 0.67981535 0.23041044 0.43331899 0.42628146]]

inv(A):
[[-1.82577672  3.69668585]
 [ 2.91167025 -3.59561693]]

inv(B):
[[ 0.73056827  4.11705064 -1.31458635]
 [-1.15719702  4.72220217 -0.40478734]
 [ 0.78142009 -7.0254787   2.14209648]]

inv(kron(A,B)):
[[ -1.33385454  -7.51681523   2.40014116   2.70068137  15.21944283
   -4.85961276]
 [  2.11278338  -8.62168681   0.73905131  -4.27779385  17.45649794
   -1

## not commutative
$$
A \otimes B \neq B \otimes A \quad \text{in general.}
$$

In [6]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[0, 5], [6, 7]])

kron_AB = np.kron(A, B)
kron_BA = np.kron(B, A)

if np.allclose(kron_AB, kron_BA):
    print("kron(A,B) == kron(B,A)")
else:
    print("kron(A,B) != kron(B,A)")
    
print("\nkron(A,B):")
print(kron_AB)
print("\nkron(B,A):")
print(kron_BA)


kron(A,B) != kron(B,A)

kron(A,B):
[[ 0  5  0 10]
 [ 6  7 12 14]
 [ 0 15  0 20]
 [18 21 24 28]]

kron(B,A):
[[ 0  0  5 10]
 [ 0  0 15 20]
 [ 6 12  7 14]
 [18 24 21 28]]


## Perfect Shuffling

But Perfect Shuffling is possible.

$$
B \otimes A = S_{m_1,m_2} (A \otimes B) S_{n_1,n_2}^T
$$

In [7]:
import numpy as np

def perfect_shuffle_matrix(m1, m2):
    S = np.zeros(shape=(m1*m2, m1*m2))
    for k in range(m2):
        for i in range(m1):
            S[k*m1+i, i*m2+k] = 1
    return S
    
# Define matrices A and B
m1, n1 = 2, 2
m2, n2 = 3, 4

A = np.random.randint(1, 9, size=(m1,n1))
B = np.random.randint(1, 9, size=(m2,n2))

# Compute Kronecker products
kron_AB = np.kron(A, B)
kron_BA = np.kron(B, A)

# Compute Perfect Shuffle matrix
P = perfect_shuffle_matrix(m1, m2)
Q = (perfect_shuffle_matrix(n1, n2)).T

# Verify the property: P @ kron_BA @ P.T should equal kron_AB
result =  P @ kron_AB @ Q
is_equal = np.allclose(result, kron_BA)

if is_equal:
    print("Perfect Shuffling is possible.")
    print("\nkron_BA == P @ kron_AB @ Q")
else:
    print("Something strange")

print("\nA:")
print(A)
print("\nB:")
print(B)
print("\nkron_AB:")
print(kron_AB)
print("\nkron_BA:")
print(kron_BA)
print("\nP:")
print(P)
print("\nQ:")
print(Q)
print("\nis_equal: ")
print(is_equal)
print("\nresult P @ kron_AB @ Q:")
print(result)

# kron_AB, kron_BA, P, Q, is_equal, result

Perfect Shuffling is possible.

kron_BA == P @ kron_AB @ Q

A:
[[5 3]
 [3 8]]

B:
[[4 8 1 5]
 [1 6 6 1]
 [2 3 5 1]]

kron_AB:
[[20 40  5 25 12 24  3 15]
 [ 5 30 30  5  3 18 18  3]
 [10 15 25  5  6  9 15  3]
 [12 24  3 15 32 64  8 40]
 [ 3 18 18  3  8 48 48  8]
 [ 6  9 15  3 16 24 40  8]]

kron_BA:
[[20 12 40 24  5  3 25 15]
 [12 32 24 64  3  8 15 40]
 [ 5  3 30 18 30 18  5  3]
 [ 3  8 18 48 18 48  3  8]
 [10  6 15  9 25 15  5  3]
 [ 6 16  9 24 15 40  3  8]]

P:
[[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]

Q:
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]

is_equal: 
True

result P @ kron_AB @ Q:
[[20. 12. 40. 24.  5.  3. 25. 15.]
 [12. 32. 24. 64.  3.  8. 15. 40.]
 [ 5.  3. 30. 18. 30. 18.  5.  3.]
 [ 3.  8. 18. 48. 18. 48.  3.  8.]
 [10