In [35]:
import numpy as np
from scipy.special import logsumexp

In [36]:
####################################
# logsumexp's input : 1d array
#===================================

In [37]:
x = np.array([-1000, -2000, -3000])

In [38]:
logsumexp(x) # logsumexp prevents underflow

-1000.0

In [39]:
sumexp = np.exp(x).sum() # underflow
sumexp

0.0

In [40]:
y = np.log(sumexp) # zero division warning

C:\Users\t0\AppData\Local\Temp\ipykernel_11408\4055062826.py:1: RuntimeWarning: divide by zero encountered in log
  y = np.log(sumexp) # zero division warning


In [41]:
# instead, calculate y = xmax + log(sum(exp(new_x)))
xmax=x.max() # -1000
new_x = x - xmax
new_x

array([    0, -1000, -2000])

In [42]:
sumexp= np.exp(new_x).sum() 
y = xmax + np.log(sumexp) 
y

-1000.0

In [43]:
error = y - logsumexp(x)
error

0.0

In [44]:
####################################
# logsumexp's input: 2d-array
#===================================

In [45]:
import numpy as np
from scipy.special import logsumexp

In [46]:
X = np.array([[-1000, -2000, -3000], [-2000, -2500, -3000], [-50, -40, -1000], [-100, -500, -400]])

In [47]:
X

array([[-1000, -2000, -3000],
       [-2000, -2500, -3000],
       [  -50,   -40, -1000],
       [ -100,  -500,  -400]])

In [48]:
# logsumexp
logsumexp(X, axis=1)

array([-1000.       , -2000.       ,   -39.9999546,  -100.       ])

In [49]:
# do the same thing with 2d numpy array

In [50]:
Xmax = X.max(axis=1)

In [51]:
Xmax

array([-1000, -2000,   -40,  -100])

In [52]:
Xmax[..., np.newaxis]

array([[-1000],
       [-2000],
       [  -40],
       [ -100]])

In [53]:
new_X = X - Xmax[..., np.newaxis]
new_X

array([[    0, -1000, -2000],
       [    0,  -500, -1000],
       [  -10,     0,  -960],
       [    0,  -400,  -300]])

In [54]:
sumexps = np.exp(new_X)
sumexps

array([[1.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [1.00000000e+000, 7.12457641e-218, 0.00000000e+000],
       [4.53999298e-005, 1.00000000e+000, 0.00000000e+000],
       [1.00000000e+000, 1.91516960e-174, 5.14820022e-131]])

In [55]:
Y = Xmax + np.log(sumexps.sum(axis=1))
Y

array([-1000.       , -2000.       ,   -39.9999546,  -100.       ])

In [56]:
errors = (Y - logsumexp(X, axis=1))**2
errors

array([0., 0., 0., 0.])