## Matrix multiplication

In [1]:
import numpy as np

n = 3
A = np.random.randint(1,10, size=(n, n)) # n by n matrix
B = np.random.randint(1,10, size=(n, n)) # n by n matrix
AB = A@B # matrix multiplication
print("\nA:")
print(A)
print("\nB:")
print(B)
print("\nAB:")
print(AB)


A:
[[6 7 6]
 [5 3 3]
 [8 2 1]]

B:
[[4 2 1]
 [6 2 7]
 [1 5 6]]

AB:
[[72 56 91]
 [41 31 44]
 [45 25 28]]


## Lower triangular and Upper triangular matrices

In [2]:
import numpy as np

n = 3
L1 = np.tril( np.random.randint(1,10,size=(n,n)))
L2 = np.tril( np.random.randint(1,10,size=(n,n)))
U1 = np.triu( np.random.randint(1,10,size=(n,n)))
U2 = np.triu( np.random.randint(1,10,size=(n,n)))

# Lower triangular matrix 
print("\nL1:")
print(L1)
print("\nL2:")
print(L2)
print("\nL1@L2:")
print(L1@L2)

# Upper triangular matrix
print("\nU1:")
print(U1)
print("\nU2:")
print(U2)
print("\nU1@U2:")
print(U1@U2)


L1:
[[1 0 0]
 [6 1 0]
 [2 3 2]]

L2:
[[4 0 0]
 [1 9 0]
 [9 1 9]]

L1@L2:
[[ 4  0  0]
 [25  9  0]
 [29 29 18]]

U1:
[[2 7 5]
 [0 7 3]
 [0 0 5]]

U2:
[[7 3 1]
 [0 5 3]
 [0 0 5]]

U1@U2:
[[14 41 48]
 [ 0 35 36]
 [ 0  0 25]]


## Doubly stochastic Matrix

In [3]:
import numpy as np

M = np.array([[2/3, 1/3],
              [1/3, 2/3]])

Mn = np.copy(M)
for i in range(20):
    Mn @= M
    if (i+2) % 5 == 0:
        print(f"\nM^{i+2}:")
        print(Mn)


M^5:
[[0.50205761 0.49794239]
 [0.49794239 0.50205761]]

M^10:
[[0.50000847 0.49999153]
 [0.49999153 0.50000847]]

M^15:
[[0.50000003 0.49999997]
 [0.49999997 0.50000003]]

M^20:
[[0.5 0.5]
 [0.5 0.5]]


## pascal matrix

https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.pascal.html

In [4]:
from scipy.linalg import pascal

n = 4
L = pascal(n, kind="lower")
U = pascal(n, kind="upper")
S = L @ U

print("\nL")
print(L)
print("\nU")
print(U)
print("\nS=LU")
print(S)


L
[[1 0 0 0]
 [1 1 0 0]
 [1 2 1 0]
 [1 3 3 1]]

U
[[1 1 1 1]
 [0 1 2 3]
 [0 0 1 3]
 [0 0 0 1]]

S=LU
[[ 1  1  1  1]
 [ 1  2  3  4]
 [ 1  3  6 10]
 [ 1  4 10 20]]


## Inner product

In [5]:


import numpy as np

n = 3
u = np.random.randint(1,10, size=(n, 1)) # column vector
v = np.random.randint(1,10, size=(n, 1)) # column vector
x = np.random.randint(1,10, size=(1,n)) # row vector
y = np.random.randint(1,10, size=(1,n)) # row vector

print("\ncolumn vector u:")
print(u)
print("\ncolumn vector v:")
print(v)
print("\nu.T@v:")
print(u.T@v)
print("\nrow vector x:")
print(x)
print("\nrow vector y:")
print(y)
print("\ninner product (x,y):")
print(np.inner(x,y))
print("\ninner product([0,1,2,3], [3,2,1,0]):")
print(np.inner([0,1,2,3], [3,2,1,0]))



column vector u:
[[4]
 [9]
 [5]]

column vector v:
[[8]
 [9]
 [2]]

u.T@v:
[[123]]

row vector x:
[[5 2 8]]

row vector y:
[[4 5 4]]

inner product (x,y):
[[62]]

inner product([0,1,2,3], [3,2,1,0]):
4


## Outer product

In [6]:
import numpy as np

n = 3
u = np.random.randint(1,10, size=(n, 1)) # column vector
v = np.random.randint(1,10, size=(n, 1)) # column vector
print("\nu:")
print(u)
print("\nv:")
print(v)
print("\nouter product: u@v.T")
print(u@v.T)


u:
[[4]
 [9]
 [4]]

v:
[[8]
 [1]
 [5]]

outer product: u@v.T
[[32  4 20]
 [72  9 45]
 [32  4 20]]


## Matrix Multiplication via Outer Products

In [7]:
import numpy as np

# Compute AB using outer product ai@bi.T where 
sum_outer_products = np.zeros(shape=(n,n))
for i in range(n):
    ai = A[:, i].reshape(-1, 1)  # Column vector
    bi = B[i].reshape(-1, 1)  # Column vector
    sum_outer_products += ai @ bi.T # Outer product

print("\na1*b1^T + ... + an*bn^t:")
print(sum_outer_products)
print("\nAB:")
print(AB)


a1*b1^T + ... + an*bn^t:
[[72. 56. 91.]
 [41. 31. 44.]
 [45. 25. 28.]]

AB:
[[72 56 91]
 [41 31 44]
 [45 25 28]]


## shuffle columns in A and rows in B

In [8]:
import numpy as np

n = 2
A = np.random.randint(1,10, size=(n, n)) # n by n matrix
B = np.random.randint(1,10, size=(n, n)) # n by n matrix

A2 = np.copy(A)
B2 = np.copy(B)
A2[:,[1,0]]=A2[:,[0,1]] # shuffle columns
B2[[1,0]] = B2[[0,1]] # shuffle rows 

print("\nA:")
print(A)
print("\nB:")
print(B)
print("\nAB:")
print(A@B)

print("\nA2(column switching):")
print(A2)
print("\nB2(row switching):")
print(B2)
print("\nA2@B2:")
print(A2@B2) # = AB



A:
[[9 1]
 [6 9]]

B:
[[8 3]
 [5 2]]

AB:
[[77 29]
 [93 36]]

A2(column switching):
[[1 9]
 [9 6]]

B2(row switching):
[[5 2]
 [8 3]]

A2@B2:
[[77 29]
 [93 36]]


## Row switching


In [9]:
import numpy as np

n = 4
A = np.random.randint(1, 10, size=(n,n)).astype(float)
R = np.eye(n)
i, j = 0, n-1
R[[i,j]] = R[[j,i]]

print("\nA:")
print(A)
print("\nR:")
print(R)
print("\nR@A")
print(R@A)


A:
[[8. 9. 9. 5.]
 [9. 8. 7. 9.]
 [1. 3. 7. 9.]
 [7. 8. 6. 1.]]

R:
[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]

R@A
[[7. 8. 6. 1.]
 [9. 8. 7. 9.]
 [1. 3. 7. 9.]
 [8. 9. 9. 5.]]


In [10]:
import numpy as np

n = 4
A = np.random.randint(1, 10, size=(n,n)).astype(float)
C = np.eye(n)
i, j = 0, n-1
C[[i,j]] = C[[j,i]]

print("\nA:")
print(A)
print("\nC:")
print(C)
print("\nA@C")
print(A@C)


A:
[[3. 9. 7. 6.]
 [2. 1. 9. 2.]
 [5. 2. 2. 7.]
 [7. 9. 5. 5.]]

C:
[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]

A@C
[[6. 9. 7. 3.]
 [2. 1. 9. 2.]
 [7. 2. 2. 5.]
 [5. 9. 5. 7.]]


 ## Elimination matrix E

In [11]:
import numpy as np

n = 4
A = np.random.randint(1, 100, size=(n,n)) # maybe det(A) != 0
E = np.eye(n)
for i in range(1, n):
    E[i, 0] = -A[i, 0]/A[0,0]

print("\nA:")
print(A)
print("\nEliminate matrix E:")
print(E)
print("\nE@A:")
print(E@A)


A:
[[52 86 65  6]
 [83 59 89 52]
 [ 8 21 42 70]
 [36 80 92 79]]

Eliminate matrix E:
[[ 1.          0.          0.          0.        ]
 [-1.59615385  1.          0.          0.        ]
 [-0.15384615  0.          1.          0.        ]
 [-0.69230769  0.          0.          1.        ]]

E@A:
[[ 52.          86.          65.           6.        ]
 [  0.         -78.26923077 -14.75        42.42307692]
 [  0.           7.76923077  32.          69.07692308]
 [  0.          20.46153846  47.          74.84615385]]


## Cyclic property of trace

In [12]:
import numpy as np

m = 5
n = 4
l = 3

A = np.random.randint(1,10, size=(m,n))
B = np.random.randint(1,10, size=(n,l))
C = np.random.randint(1,10, size=(l,m))
ABC = A@B@C
BCA = B@C@A
CAB = C@A@B

print("\nA:")
print(A)
print("\nB:")
print(B)
print("\nC:")
print(C)

print("\nABC:")
print(ABC)
print("\ntr(ABC)=", end="")
print(ABC.trace())
print("\nBCA:")
print(BCA)
print("\ntr(BCA)=", end="")
print(BCA.trace())
print("\nCAB:")
print(CAB)
print("\ntr(CAB)=", end="")
print(CAB.trace())




A:
[[1 4 4 5]
 [9 7 4 4]
 [8 9 5 1]
 [6 3 7 6]
 [4 5 5 9]]

B:
[[2 9 8]
 [5 1 9]
 [2 9 6]
 [6 9 9]]

C:
[[7 3 7 9 9]
 [5 4 8 8 8]
 [4 1 9 9 5]]

ABC:
[[1342  669 2189 2309 1857]
 [2175 1090 3630 3800 3020]
 [1950  955 3275 3429 2693]
 [2093 1098 3470 3624 2940]
 [2266 1147 3707 3901 3149]]

tr(ABC)=12480

BCA:
[[3297 3272 3138 2955]
 [2516 2508 2464 2302]
 [2979 2960 2832 2691]
 [4176 4164 4023 3843]]

tr(BCA)=12480

CAB:
[[2780 5152 5895]
 [2648 4918 5689]
 [2196 4152 4782]]

tr(CAB)=12480
