## Matrix multiplication

In [1]:
import numpy as np

n = 3
A = np.random.randint(1,10, size=(n, n)) # n by n matrix
B = np.random.randint(1,10, size=(n, n)) # n by n matrix
AB = A@B # matrix multiplication
print("\nA:")
print(A)
print("\nB:")
print(B)
print("\nAB:")
print(AB)


A:
[[5 2 9]
 [6 7 9]
 [3 4 9]]

B:
[[7 3 3]
 [2 5 5]
 [6 9 8]]

AB:
[[ 93 106  97]
 [110 134 125]
 [ 83 110 101]]


## Lower triangular and Upper triangular matrices

In [2]:
import numpy as np

n = 3
L1 = np.tril( np.random.randint(1,10,size=(n,n)))
L2 = np.tril( np.random.randint(1,10,size=(n,n)))
U1 = np.triu( np.random.randint(1,10,size=(n,n)))
U2 = np.triu( np.random.randint(1,10,size=(n,n)))

# Lower triangular matrix 
print("\nL1:")
print(L1)
print("\nL2:")
print(L2)
print("\nL1@L2:")
print(L1@L2)

# Upper triangular matrix
print("\nU1:")
print(U1)
print("\nU2:")
print(U2)
print("\nU1@U2:")
print(U1@U2)


L1:
[[9 0 0]
 [3 3 0]
 [8 8 1]]

L2:
[[3 0 0]
 [3 4 0]
 [5 2 4]]

L1@L2:
[[27  0  0]
 [18 12  0]
 [53 34  4]]

U1:
[[1 1 2]
 [0 3 1]
 [0 0 8]]

U2:
[[3 4 5]
 [0 6 1]
 [0 0 7]]

U1@U2:
[[ 3 10 20]
 [ 0 18 10]
 [ 0  0 56]]


## Doubly stochastic Matrix

In [3]:
import numpy as np

M = np.array([[2/3, 1/3],
              [1/3, 2/3]])

Mn = np.copy(M)
for i in range(20):
    Mn @= M
    if (i+2) % 5 == 0:
        print(f"\nM^{i+2}:")
        print(Mn)


M^5:
[[0.50205761 0.49794239]
 [0.49794239 0.50205761]]

M^10:
[[0.50000847 0.49999153]
 [0.49999153 0.50000847]]

M^15:
[[0.50000003 0.49999997]
 [0.49999997 0.50000003]]

M^20:
[[0.5 0.5]
 [0.5 0.5]]


## pascal matrix

https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.pascal.html

In [4]:
from scipy.linalg import pascal

n = 4
L = pascal(n, kind="lower")
U = pascal(n, kind="upper")
S = L @ U

print("\nL")
print(L)
print("\nU")
print(U)
print("\nS=LU")
print(S)


L
[[1 0 0 0]
 [1 1 0 0]
 [1 2 1 0]
 [1 3 3 1]]

U
[[1 1 1 1]
 [0 1 2 3]
 [0 0 1 3]
 [0 0 0 1]]

S=LU
[[ 1  1  1  1]
 [ 1  2  3  4]
 [ 1  3  6 10]
 [ 1  4 10 20]]


## Inner product

In [5]:


import numpy as np

n = 3
u = np.random.randint(1,10, size=(n, 1)) # column vector
v = np.random.randint(1,10, size=(n, 1)) # column vector
x = np.random.randint(1,10, size=(1,n)) # row vector
y = np.random.randint(1,10, size=(1,n)) # row vector

print("\ncolumn vector u:")
print(u)
print("\ncolumn vector v:")
print(v)
print("\nu.T@v:")
print(u.T@v)
print("\nrow vector x:")
print(x)
print("\nrow vector y:")
print(y)
print("\ninner product (x,y):")
print(np.inner(x,y))
print("\ninner product([0,1,2,3], [3,2,1,0]):")
print(np.inner([0,1,2,3], [3,2,1,0]))



column vector u:
[[9]
 [9]
 [6]]

column vector v:
[[4]
 [4]
 [9]]

u.T@v:
[[126]]

row vector x:
[[4 3 5]]

row vector y:
[[8 9 5]]

inner product (x,y):
[[84]]

inner product([0,1,2,3], [3,2,1,0]):
4


## Outer product

In [6]:
import numpy as np

n = 3
u = np.random.randint(1,10, size=(n, 1)) # column vector
v = np.random.randint(1,10, size=(n, 1)) # column vector
print("\nu:")
print(u)
print("\nv:")
print(v)
print("\nouter product: u@v.T")
print(u@v.T)


u:
[[1]
 [5]
 [1]]

v:
[[9]
 [8]
 [8]]

outer product: u@v.T
[[ 9  8  8]
 [45 40 40]
 [ 9  8  8]]


## Matrix Multiplication via Outer Products

In [7]:
import numpy as np

# Compute AB using outer product ai@bi.T where 
sum_outer_products = np.zeros(shape=(n,n))
for i in range(n):
    ai = A[:, i].reshape(-1, 1)  # Column vector
    bi = B[i].reshape(-1, 1)  # Column vector
    sum_outer_products += ai @ bi.T # Outer product

print("\na1*b1^T + ... + an*bn^t:")
print(sum_outer_products)
print("\nAB:")
print(AB)


a1*b1^T + ... + an*bn^t:
[[ 93. 106.  97.]
 [110. 134. 125.]
 [ 83. 110. 101.]]

AB:
[[ 93 106  97]
 [110 134 125]
 [ 83 110 101]]


## shuffle columns in A and rows in B

In [8]:
import numpy as np

n = 2
A = np.random.randint(1,10, size=(n, n)) # n by n matrix
B = np.random.randint(1,10, size=(n, n)) # n by n matrix

A2 = np.copy(A)
B2 = np.copy(B)
A2[:,[1,0]]=A2[:,[0,1]] # shuffle columns
B2[[1,0]] = B2[[0,1]] # shuffle rows 

print("\nA:")
print(A)
print("\nB:")
print(B)
print("\nAB:")
print(A@B)

print("\nA2(column switching):")
print(A2)
print("\nB2(row switching):")
print(B2)
print("\nA2@B2:")
print(A2@B2) # = AB



A:
[[6 1]
 [5 9]]

B:
[[5 4]
 [5 8]]

AB:
[[35 32]
 [70 92]]

A2(column switching):
[[1 6]
 [9 5]]

B2(row switching):
[[5 8]
 [5 4]]

A2@B2:
[[35 32]
 [70 92]]


## Row switching


In [9]:
import numpy as np

n = 4
A = np.random.randint(1, 10, size=(n,n)).astype(float)
R = np.eye(n)
i, j = 0, n-1
R[[i,j]] = R[[j,i]]

print("\nA:")
print(A)
print("\nR:")
print(R)
print("\nR@A")
print(R@A)


A:
[[2. 3. 5. 4.]
 [7. 4. 1. 6.]
 [6. 9. 7. 5.]
 [5. 6. 3. 7.]]

R:
[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]

R@A
[[5. 6. 3. 7.]
 [7. 4. 1. 6.]
 [6. 9. 7. 5.]
 [2. 3. 5. 4.]]


## Column switching

In [11]:
import numpy as np

n = 4
A = np.random.randint(1, 10, size=(n,n)).astype(float)
C = np.eye(n)
i, j = 0, n-1
C[[i,j]] = C[[j,i]]

print("\nA:")
print(A)
print("\nC:")
print(C)
print("\nA@C")
print(A@C)


A:
[[9. 8. 7. 3.]
 [1. 6. 2. 6.]
 [5. 9. 1. 9.]
 [2. 9. 5. 7.]]

C:
[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]

A@C
[[3. 8. 7. 9.]
 [6. 6. 2. 1.]
 [9. 9. 1. 5.]
 [7. 9. 5. 2.]]


# Row/column scaling


In [12]:
import numpy as np

n = 3
A = np.array([[2, 2, 2],
              [4, 4, 4],
              [6, 6, 6],])

B = np.ones((n,n))
D = np.diag([-1, 1, -1])
C = D @ B @ D
S = np.diag(1/A[:,0])

print("\nA:")
print(A)
print("\nB:")
print(B)
print("\nD:")
print(D)
print("\nC=D@B@D:")
print(C)
print("\nS:")
print(S)
print("\nS@A:")
print(S@A)
print("\nB@S:")
print(B@S)


A:
[[2 2 2]
 [4 4 4]
 [6 6 6]]

B:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

D:
[[-1  0  0]
 [ 0  1  0]
 [ 0  0 -1]]

C=D@B@D:
[[ 1. -1.  1.]
 [-1.  1. -1.]
 [ 1. -1.  1.]]

S:
[[0.5        0.         0.        ]
 [0.         0.25       0.        ]
 [0.         0.         0.16666667]]

S@A:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

B@S:
[[0.5        0.25       0.16666667]
 [0.5        0.25       0.16666667]
 [0.5        0.25       0.16666667]]


 ## Elimination matrix E

In [13]:
import numpy as np

n = 4
A = np.random.randint(1, 100, size=(n,n)) # maybe det(A) != 0
E = np.eye(n)
for i in range(1, n):
    E[i, 0] = -A[i, 0]/A[0,0]

print("\nA:")
print(A)
print("\nEliminate matrix E:")
print(E)
print("\nE@A:")
print(E@A)


A:
[[52 59 14 73]
 [95 93  4 55]
 [36 32 50 27]
 [51 13 20 50]]

Eliminate matrix E:
[[ 1.          0.          0.          0.        ]
 [-1.82692308  1.          0.          0.        ]
 [-0.69230769  0.          1.          0.        ]
 [-0.98076923  0.          0.          1.        ]]

E@A:
[[ 52.          59.          14.          73.        ]
 [  0.         -14.78846154 -21.57692308 -78.36538462]
 [  0.          -8.84615385  40.30769231 -23.53846154]
 [  0.         -44.86538462   6.26923077 -21.59615385]]


## Cyclic property of trace

In [14]:
import numpy as np

m = 5
n = 4
l = 3

A = np.random.randint(1,10, size=(m,n))
B = np.random.randint(1,10, size=(n,l))
C = np.random.randint(1,10, size=(l,m))
ABC = A@B@C
BCA = B@C@A
CAB = C@A@B

print("\nA:")
print(A)
print("\nB:")
print(B)
print("\nC:")
print(C)

print("\nABC:")
print(ABC)
print("\ntr(ABC)=", end="")
print(ABC.trace())
print("\nBCA:")
print(BCA)
print("\ntr(BCA)=", end="")
print(BCA.trace())
print("\nCAB:")
print(CAB)
print("\ntr(CAB)=", end="")
print(CAB.trace())




A:
[[6 4 7 7]
 [6 3 3 1]
 [9 3 6 1]
 [2 8 5 7]
 [4 5 3 3]]

B:
[[3 2 8]
 [9 9 8]
 [4 7 9]
 [8 7 8]]

C:
[[3 3 9 2 3]
 [6 3 3 5 4]
 [6 6 2 7 4]]

ABC:
[[2484 2046 2078 2399 1794]
 [1239 1038 1000 1214  891]
 [1770 1488 1372 1748 1266]
 [2508 2028 2228 2375 1826]
 [1587 1302 1368 1522 1151]]

tr(ABC)=8420

BCA:
[[1573 1433 1473 1246]
 [3120 2621 2833 2247]
 [2361 2146 2225 1888]
 [2773 2338 2518 2001]]

tr(BCA)=8420

CAB:
[[1970 2090 3071]
 [2423 2539 3386]
 [2840 2966 3911]]

tr(CAB)=8420
