## Matrix multiplication

In [1]:
import numpy as np

n = 3
A = np.random.randint(1,5, size=(n, n)) # n by n matrix
B = np.random.randint(1,5, size=(n, n)) # n by n matrix
AB = A@B # matrix multiplication
print("\nA:")
print(A)
print("\nB:")
print(B)
print("\nAB:")
print(AB)


A:
[[2 3 2]
 [1 1 3]
 [4 4 2]]

B:
[[4 1 2]
 [2 3 4]
 [1 4 2]]

AB:
[[16 19 20]
 [ 9 16 12]
 [26 24 28]]


## Lower triangular and Upper triangular matrices

In [2]:
import numpy as np

n = 3
L1 = np.tril( np.random.randint(1,10,size=(n,n)))
L2 = np.tril( np.random.randint(1,10,size=(n,n)))
U1 = np.triu( np.random.randint(1,10,size=(n,n)))
U2 = np.triu( np.random.randint(1,10,size=(n,n)))

# Lower triangular matrix 
print("\nL1:")
print(L1)
print("\nL2:")
print(L2)
print("\nL1@L2:")
print(L1@L2)

# Upper triangular matrix
print("\nU1:")
print(U1)
print("\nU2:")
print(U2)
print("\nU1@U2:")
print(U1@U2)


L1:
[[8 0 0]
 [5 5 0]
 [9 3 8]]

L2:
[[9 0 0]
 [7 7 0]
 [6 6 8]]

L1@L2:
[[ 72   0   0]
 [ 80  35   0]
 [150  69  64]]

U1:
[[1 5 2]
 [0 4 2]
 [0 0 9]]

U2:
[[7 1 5]
 [0 7 1]
 [0 0 7]]

U1@U2:
[[ 7 36 24]
 [ 0 28 18]
 [ 0  0 63]]


## Doubly stochastic Matrix

In [3]:
import numpy as np

M = np.array([[2/3, 1/3],
              [1/3, 2/3]])

Mn = np.copy(M)
for i in range(20):
    Mn @= M
    if (i+2) % 5 == 0:
        print(f"\nM^{i+2}:")
        print(Mn)


M^5:
[[0.50205761 0.49794239]
 [0.49794239 0.50205761]]

M^10:
[[0.50000847 0.49999153]
 [0.49999153 0.50000847]]

M^15:
[[0.50000003 0.49999997]
 [0.49999997 0.50000003]]

M^20:
[[0.5 0.5]
 [0.5 0.5]]


## pascal matrix

https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.pascal.html

In [4]:
from scipy.linalg import pascal

n = 4
L = pascal(n, kind="lower")
U = pascal(n, kind="upper")
S = L @ U

print("\nL")
print(L)
print("\nU")
print(U)
print("\nS=LU")
print(S)


L
[[1 0 0 0]
 [1 1 0 0]
 [1 2 1 0]
 [1 3 3 1]]

U
[[1 1 1 1]
 [0 1 2 3]
 [0 0 1 3]
 [0 0 0 1]]

S=LU
[[ 1  1  1  1]
 [ 1  2  3  4]
 [ 1  3  6 10]
 [ 1  4 10 20]]


## Inner product

In [5]:


import numpy as np

n = 3
u = np.random.randint(1,10, size=(n, 1)) # column vector
v = np.random.randint(1,10, size=(n, 1)) # column vector
x = np.random.randint(1,10, size=(1,n)) # row vector
y = np.random.randint(1,10, size=(1,n)) # row vector

print("\ncolumn vector u:")
print(u)
print("\ncolumn vector v:")
print(v)
print("\nu.T@v:")
print(u.T@v)
print("\nrow vector x:")
print(x)
print("\nrow vector y:")
print(y)
print("\ninner product (x,y):")
print(np.inner(x,y))
print("\ninner product([0,1,2,3], [3,2,1,0]):")
print(np.inner([0,1,2,3], [3,2,1,0]))



column vector u:
[[9]
 [5]
 [8]]

column vector v:
[[7]
 [8]
 [8]]

u.T@v:
[[167]]

row vector x:
[[5 2 7]]

row vector y:
[[7 7 5]]

inner product (x,y):
[[84]]

inner product([0,1,2,3], [3,2,1,0]):
4


## Outer product

In [6]:
import numpy as np

n = 3
u = np.random.randint(1,10, size=(n, 1)) # column vector
v = np.random.randint(1,10, size=(n, 1)) # column vector
print("\nu:")
print(u)
print("\nv:")
print(v)
print("\nouter product: u@v.T")
print(u@v.T)


u:
[[3]
 [7]
 [9]]

v:
[[3]
 [4]
 [1]]

outer product: u@v.T
[[ 9 12  3]
 [21 28  7]
 [27 36  9]]


## Matrix Multiplication via Outer Products

In [7]:
import numpy as np

# Compute AB using outer product ai@bi.T where 
sum_outer_products = np.zeros(shape=(n,n))
for i in range(n):
    ai = A[:, i].reshape(-1, 1)  # Column vector
    bi = B[i].reshape(-1, 1)  # Column vector
    sum_outer_products += ai @ bi.T # Outer product

print("\na1*b1^T + ... + an*bn^t:")
print(sum_outer_products)
print("\nAB:")
print(AB)


a1*b1^T + ... + an*bn^t:
[[16. 19. 20.]
 [ 9. 16. 12.]
 [26. 24. 28.]]

AB:
[[16 19 20]
 [ 9 16 12]
 [26 24 28]]


## shuffle columns in A and rows in B

In [8]:
import numpy as np

n = 2
A = np.random.randint(1,10, size=(n, n)) # n by n matrix
B = np.random.randint(1,10, size=(n, n)) # n by n matrix

A2 = np.copy(A)
B2 = np.copy(B)
A2[:,[1,0]]=A2[:,[0,1]] # shuffle columns
B2[[1,0]] = B2[[0,1]] # shuffle rows 

print("\nA:")
print(A)
print("\nB:")
print(B)
print("\nAB:")
print(A@B)

print("\nA2(column switching):")
print(A2)
print("\nB2(row switching):")
print(B2)
print("\nA2@B2:")
print(A2@B2) # = AB



A:
[[4 9]
 [2 9]]

B:
[[2 6]
 [4 1]]

AB:
[[44 33]
 [40 21]]

A2(column switching):
[[9 4]
 [9 2]]

B2(row switching):
[[4 1]
 [2 6]]

A2@B2:
[[44 33]
 [40 21]]


## Row switching


In [9]:
import numpy as np

n = 4
A = np.random.randint(1, 10, size=(n,n)).astype(float)
R = np.eye(n)
i, j = 0, n-1
R[[i,j]] = R[[j,i]]

print("\nA:")
print(A)
print("\nR:")
print(R)
print("\nR@A")
print(R@A)


A:
[[6. 6. 9. 5.]
 [8. 3. 3. 7.]
 [1. 8. 6. 1.]
 [5. 8. 7. 7.]]

R:
[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]

R@A
[[5. 8. 7. 7.]
 [8. 3. 3. 7.]
 [1. 8. 6. 1.]
 [6. 6. 9. 5.]]


## Column switching

In [10]:
import numpy as np

n = 4
A = np.random.randint(1, 10, size=(n,n)).astype(float)
C = np.eye(n)
i, j = 0, n-1
C[[i,j]] = C[[j,i]]

print("\nA:")
print(A)
print("\nC:")
print(C)
print("\nA@C")
print(A@C)


A:
[[9. 4. 7. 4.]
 [5. 2. 7. 7.]
 [9. 6. 5. 7.]
 [1. 2. 6. 8.]]

C:
[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]

A@C
[[4. 4. 7. 9.]
 [7. 2. 7. 5.]
 [7. 6. 5. 9.]
 [8. 2. 6. 1.]]


# Row/column scaling


In [11]:
import numpy as np

n = 3
A = np.array([[2, 2, 2],
              [4, 4, 4],
              [6, 6, 6],])

B = np.ones((n,n))
D = np.diag([-1, 1, -1])
C = D @ B @ D
S = np.diag(1/A[:,0])

print("\nA:")
print(A)
print("\nB:")
print(B)
print("\nD:")
print(D)
print("\nC=D@B@D:")
print(C)
print("\nS:")
print(S)
print("\nS@A:")
print(S@A)
print("\nB@S:")
print(B@S)


A:
[[2 2 2]
 [4 4 4]
 [6 6 6]]

B:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

D:
[[-1  0  0]
 [ 0  1  0]
 [ 0  0 -1]]

C=D@B@D:
[[ 1. -1.  1.]
 [-1.  1. -1.]
 [ 1. -1.  1.]]

S:
[[0.5        0.         0.        ]
 [0.         0.25       0.        ]
 [0.         0.         0.16666667]]

S@A:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

B@S:
[[0.5        0.25       0.16666667]
 [0.5        0.25       0.16666667]
 [0.5        0.25       0.16666667]]


 ## Elimination matrix E

In [12]:
import numpy as np

n = 4
A = np.random.randint(1, 100, size=(n,n)) # maybe det(A) != 0
E = np.eye(n)
for i in range(1, n):
    E[i, 0] = -A[i, 0]/A[0,0]

print("\nA:")
print(A)
print("\nEliminate matrix E:")
print(E)
print("\nE@A:")
print(E@A)


A:
[[75 93 58 79]
 [44 97 60 75]
 [87 99 58 11]
 [86 95 85 51]]

Eliminate matrix E:
[[ 1.          0.          0.          0.        ]
 [-0.58666667  1.          0.          0.        ]
 [-1.16        0.          1.          0.        ]
 [-1.14666667  0.          0.          1.        ]]

E@A:
[[ 75.          93.          58.          79.        ]
 [  0.          42.44        25.97333333  28.65333333]
 [  0.          -8.88        -9.28       -80.64      ]
 [  0.         -11.64        18.49333333 -39.58666667]]


## Cyclic property of trace

In [13]:
import numpy as np

m = 5
n = 4
l = 3

A = np.random.randint(1,10, size=(m,n))
B = np.random.randint(1,10, size=(n,l))
C = np.random.randint(1,10, size=(l,m))
ABC = A@B@C
BCA = B@C@A
CAB = C@A@B

print("\nA:")
print(A)
print("\nB:")
print(B)
print("\nC:")
print(C)

print("\nABC:")
print(ABC)
print("\ntr(ABC)=", end="")
print(ABC.trace())
print("\nBCA:")
print(BCA)
print("\ntr(BCA)=", end="")
print(BCA.trace())
print("\nCAB:")
print(CAB)
print("\ntr(CAB)=", end="")
print(CAB.trace())




A:
[[9 5 6 5]
 [1 3 4 7]
 [8 9 8 1]
 [8 4 4 7]
 [9 8 4 8]]

B:
[[1 5 2]
 [4 6 1]
 [2 3 4]
 [2 3 3]]

C:
[[8 1 2 4 5]
 [5 2 4 2 8]
 [5 9 3 1 5]]

ABC:
[[1258  825  720  482 1429]
 [ 770  525  420  294  833]
 [1401  844  788  550 1578]
 [1138  753  651  435 1291]
 [1495  917  844  584 1687]]

tr(ABC)=4693

BCA:
[[1263 1058  882  998]
 [1797 1425 1190 1332]
 [1357 1143  994 1149]
 [1226 1020  880 1011]]

tr(BCA)=4693

CAB:
[[1076 2195 1216]
 [1185 2362 1276]
 [1127 2149 1255]]

tr(CAB)=4693
