In [2]:
import numpy as np
A = np.array([[1, 2],[-1,-1]])
x = np.array([2,4])

In [5]:
A

array([[ 1,  2],
       [-1, -1]])

In [4]:
x

array([2, 4])

In [6]:
x.T

array([2, 4])

In [8]:
x[:, np.newaxis]

array([[2],
       [4]])

In [12]:
A * x

array([[ 2,  4],
       [-4, -4]])

In [13]:
x = np.array([[2],[4]])

In [14]:
A*x

array([[ 2,  4],
       [-4, -4]])