# Northwest and Southeast matrices


## Definition
* B: n by n Northwest matrix
* C: n by n Southeast matrix

$$
B \in \mathbf{R^{n\times n}} \text{ is northwest} \iff
b_{ij} = 0 \quad \text{for all} \quad i + j > n+1.
$$



$$
C \in \mathbf{R^{n\times n}} \text{ is southeast}  \iff
c_{ij} = 0 \quad \text{for all} \quad i + j < n+1.
$$

If i,j=0,1,...,n-1, use $i+j > n-1$ and $i+j < n-1$, instead of $i+j > n+1$ and $i+j < n+1$.

## Example
$
B = \begin{bmatrix}
1 & 1 & 1 \\
1 & 1 & 0 \\
1 & 0 & 0 \\
\end{bmatrix}
$

$
C = \begin{bmatrix}
0 & 0 & 1 \\
0 & 1 & 1 \\
1 & 1 & 1 \\
\end{bmatrix}
$



## Inverse of Northweast and Southeast matrices

$$
\begin{aligned}
\text{northwest matrix } B & = (b_{ij}) \\
& = \begin{bmatrix}
b_{11} & b_{12} & b_{13} & \cdots & b_{1,n-1}  & b_{1,n} \\
b_{21} & b_{22} & b_{23} & \cdots & b_{2,n-1} & 0 \\
b_{31} & b_{32} & b_{33} & \cdots & 0 & 0 \\
\vdots & \vdots & \vdots & \ddots & \vdots & \vdots \\
b_{n1} & 0 & 0 & \cdots & 0 & 0
\end{bmatrix}
\end{aligned}
$$

then 
$$
B^{-1} = \begin{bmatrix}
0 & 0 & 0 & \cdots & 0 & b_{n,1}^{-1} \\
0 & 0 & 0 & \cdots & b_{n-1,2}^{-1} & * \\
0 & 0 & 0 & \cdots & * & * \\
\vdots & \vdots & \vdots & \ddots & \vdots & *\\
b_{1,n}^{-1} & * & * & \cdots & * & *
\end{bmatrix}
$$


In [1]:
import numpy as np
from scipy.linalg import pascal


n = 5

# Create a northwest matrix B
B = (np.random.randint(1,10, size=(n,n)))
for i in range(n):
    for j in range(n):
        if i+j > n-1:
            B[i,j]=0

# Create a southeast matrix
C = (np.random.randint(1,10, size=(n,n)))
for i in range(n):
    for j in range(n):
        if i+j < n-1:
            C[i,j]=0

Binv = np.linalg.inv(B)
Cinv = np.linalg.inv(C)

print("Northwest Matrix B:")
print(B)
print("\nInv(B):")
print(np.round(Binv, decimals=4))
print("\nSoutheast Matrix C:")
print(C)
print("\nInv(C):")
print(np.round(Cinv, decimals=4))

Northwest Matrix B:
[[5 5 1 4 5]
 [6 2 2 4 0]
 [4 6 9 0 0]
 [7 2 0 0 0]
 [9 0 0 0 0]]

Inv(B):
[[ 0.      0.      0.      0.      0.1111]
 [-0.      0.      0.      0.5    -0.3889]
 [ 0.     -0.      0.1111 -0.3333  0.2099]
 [ 0.      0.25   -0.0556 -0.0833 -0.0772]
 [ 0.2    -0.2     0.0222 -0.3667  0.2975]]

Southeast Matrix C:
[[0 0 0 0 9]
 [0 0 0 4 9]
 [0 0 5 1 3]
 [0 9 2 8 1]
 [4 5 1 9 5]]

Inv(C):
[[ 0.1608 -0.2861  0.0056 -0.1389  0.25  ]
 [ 0.2136 -0.2111 -0.0444  0.1111  0.    ]
 [-0.0167 -0.05    0.2     0.      0.    ]
 [-0.25    0.25   -0.     -0.     -0.    ]
 [ 0.1111  0.      0.      0.      0.    ]]


## Product of B and C

$$
\begin{aligned}
B C & = \begin{bmatrix}
b_{11} & b_{12} & b_{13} & \cdots & b_{1,n-1}  & b_{1,n} \\
b_{21} & b_{22} & b_{23} & \cdots & b_{2,n-1} & 0 \\
b_{31} & b_{32} & b_{33} & \cdots & 0 & 0 \\
\vdots & \cdot^{\cdot^{\cdot}} & \vdots & \vdots & \vdots & \vdots \\
b_{n1} & 0 & 0 & \cdots & 0 & 0
\end{bmatrix}
\begin{bmatrix}
0 & 0& 0 & \cdots & 0  & c_{1,n} \\
0 & 0 & 0 & \cdots & c_{2,n-1} & c_{2,n} \\
0 & 0 & 0 & \cdot^{\cdot^{\cdot}} & c_{3,n-1} & c_{3,n} \\
\vdots & \vdots & \vdots & \vdots & \vdots & \vdots \\
c_{n1} & c_{n2} & c_{n3} & \cdots & c_{n,n-1} & c_{n,n}
\end{bmatrix} \\
& = \begin{bmatrix}
b_{1,n} c_{n,1} & * & * & \cdots & * \\
0 & b_{2,n-1} c_{n-1,2} & * & \cdots & * \\
0 & 0 & b_{3,n-2} c_{n-2,3} & \cdots & * \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
0 & 0 & 0 & \cdots & b_{n,1} c_{1,n}
\end{bmatrix}
\end{aligned}
$$


In [2]:
print("B:")
print(B)
print("\nC:")
print(C)
print("\nBC:")
print(np.dot(B,C))
print("\nCB:")
print(np.dot(C,B))

B:
[[5 5 1 4 5]
 [6 2 2 4 0]
 [4 6 9 0 0]
 [7 2 0 0 0]
 [9 0 0 0 0]]

C:
[[0 0 0 0 9]
 [0 0 0 4 9]
 [0 0 5 1 3]
 [0 9 2 8 1]
 [4 5 1 9 5]]

BC:
[[ 20  61  18  98 122]
 [  0  36  18  42  82]
 [  0   0  45  33 117]
 [  0   0   0   8  81]
 [  0   0   0   0  81]]

CB:
[[ 81   0   0   0   0]
 [109   8   0   0   0]
 [ 54  32  45   0   0]
 [127  46  36  36   0]
 [162  54  23  36  20]]


## why is BC upper triangular ?

$$
(BC)_{ij} = \sum_{k=1}^n b_{ik} c_{kj} 
$$

$$
\begin{aligned}
i+k > n+1 \Rightarrow b_{ik} = 0 \\
k+j < n+1 \Rightarrow c_{kj} = 0 \\
\end{aligned}
$$

$$
 k > n+1-i \text{ and } k < n+1-j  \Rightarrow b_{ik} c_{kj} = 0 
$$

When the two regions $k>n+1-i$ and $k<n+1-j$  overlaped, $b_{ik} c_{kj} = 0 \quad \forall k$

$$
k>n+1-i \text{ and } k<n+1-j \quad \forall k \quad \Rightarrow (BC)_{ij} = 0
$$
See the following interactive plot.

In [11]:
import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interactive, IntSlider


def plot_regions(i, j):
    # Compute BCij
    bcij = 0
    n = len(B)
    for k in range(n):
        bcij += B[i-1][k]*C[k][j-1]
    print(f"(BC){i},{j} = ", end="")
    print(bcij)
    print("\nBC:")
    print(np.dot(B,C))

    
    k_values = np.linspace(0, n+1, 500)
    fig, ax = plt.subplots(figsize=(8, 2))

    # Plot the region where k < n+1-i
    ax.fill_between(k_values, 0, 1, where=(k_values > n+1-i), color='blue', alpha=0.3, label='$k < n+1-i$')
    ax.axvline(x=n+1-i, color='black', linestyle='--', label='$k=n+1-i$')

    # Plot the region where k > n+1-j
    ax.fill_between(k_values, 0, 1, where=(k_values < n+1-j), color='red', alpha=0.3, label='$k > n+1-j$')
    ax.axvline(x=n+1-j, color='black', linestyle='--', label='$k=n+1-j$')

    # Set the labels and title
    ax.set_title('Regions for $k < n+1-i$ and $k > n+1-j$', fontsize=14)
    ax.set_xlabel('$k$', fontsize=12)
    ax.set_yticks([])  # Remove y-axis labels
    ax.legend(loc='upper left')

    # Show grid and plot
    ax.grid(True)
    ax.set_xlim([0, n+1])
    plt.show()

# Create sliders for i and j
slider_i = IntSlider(value=3, min=1, max=5, step=1, description='i:')
slider_j = IntSlider(value=3, min=1, max=5, step=1, description='j:')

# Create the interactive plot
interactive_plot = interactive(plot_regions, i=slider_i, j=slider_j)
interactive_plot

interactive(children=(IntSlider(value=3, description='i:', max=5, min=1), IntSlider(value=3, description='j:',…

## transpose(B)

If $B$ is northwest then $B^T$ is also northwest.

In [4]:
print("B:")
print(B)
print("\ntranspose(B)")
print(B.T)

B:
[[5 5 1 4 5]
 [6 2 2 4 0]
 [4 6 9 0 0]
 [7 2 0 0 0]
 [9 0 0 0 0]]

transpose(B)
[[5 6 4 7 9]
 [5 2 6 2 0]
 [1 2 9 0 0]
 [4 4 0 0 0]
 [5 0 0 0 0]]


## Reference 
* Introduction to Linear algebra 5th edition (Prob36 in chapter 2.7)
