# Northwest and Southeast matrices


## Definition
* B: n by n Northwest matrix
* C: n by n Southeast matrix

$$
B \in \mathbf{R^{n\times n}} \text{ is northwest} \iff
b_{ij} = 0 \quad \text{for all} \quad i + j > n+1.
$$



$$
C \in \mathbf{R^{n\times n}} \text{ is southeast}  \iff
c_{ij} = 0 \quad \text{for all} \quad i + j < n+1.
$$

If i,j=0,1,...,n-1, use $i+j > n-1$ and $i+j < n-1$, instead of $i+j > n+1$ and $i+j < n+1$.

## Example
$
B = \begin{bmatrix}
1 & 1 & 1 \\
1 & 0 & 0 \\
1 & 0 & 0 \\
\end{bmatrix}
$

$
C = \begin{bmatrix}
0 & 0 & 1 \\
0 & 1 & 1 \\
1 & 1 & 1 \\
\end{bmatrix}
$



## Inverse of Northweast and Southeast matrices

$$
\begin{aligned}
\text{northwest matrix } B & = (b_{ij}) \\
& = \begin{bmatrix}
b_{11} & b_{12} & b_{13} & \cdots & b_{1,n-1}  & b_{1,n} \\
b_{21} & b_{22} & b_{23} & \cdots & b_{2,n-1} & 0 \\
b_{31} & b_{32} & b_{33} & \cdots & 0 & 0 \\
\vdots & \vdots & \vdots & \ddots & \vdots & \vdots \\
b_{n1} & 0 & 0 & \cdots & 0 & 0
\end{bmatrix}
\end{aligned}
$$

then 
$$
B^{-1} = \begin{bmatrix}
0 & 0 & 0 & \cdots & 0 & b_{n,1}^{-1} \\
0 & 0 & 0 & \cdots & b_{n-1,2}^{-1} & * \\
0 & 0 & 0 & \cdots & * & * \\
\vdots & \vdots & \vdots & \ddots & \vdots & *\\
b_{1,n}^{-1} & * & * & \cdots & * & *
\end{bmatrix}
$$


In [1]:
import numpy as np
from scipy.linalg import pascal


n = 5

# Create a northwest matrix B
B = (np.random.randint(1,10, size=(n,n)))
for i in range(n):
    for j in range(n):
        if i+j > n-1:
            B[i,j]=0

# Create a southeast matrix
C = (np.random.randint(1,10, size=(n,n)))
for i in range(n):
    for j in range(n):
        if i+j < n-1:
            C[i,j]=0

Binv = np.linalg.inv(B)
Cinv = np.linalg.inv(C)

print("Northwest Matrix B:")
print(B)
print("\nInv(B):")
print(np.round(Binv, decimals=4))
print("\nSoutheast Matrix C:")
print(C)
print("\nInv(C):")
print(np.round(Cinv, decimals=4))

Northwest Matrix B:
[[5 7 6 4 5]
 [2 2 5 3 0]
 [3 1 1 0 0]
 [2 1 0 0 0]
 [9 0 0 0 0]]

Inv(B):
[[ 0.      0.      0.      0.      0.1111]
 [-0.     -0.      0.      1.     -0.2222]
 [-0.      0.      1.     -1.     -0.1111]
 [ 0.      0.3333 -1.6667  1.      0.2593]
 [ 0.2    -0.2667  0.1333 -1.      0.1259]]

Southeast Matrix C:
[[0 0 0 0 2]
 [0 0 0 6 6]
 [0 0 6 6 5]
 [0 5 1 7 6]
 [5 4 5 8 8]]

Inv(C):
[[-0.15    0.06   -0.14   -0.16    0.2   ]
 [ 0.0833 -0.2    -0.0333  0.2     0.    ]
 [ 0.0833 -0.1667  0.1667  0.      0.    ]
 [-0.5     0.1667 -0.     -0.     -0.    ]
 [ 0.5     0.      0.      0.      0.    ]]


## Product of B and C

$$
\begin{aligned}
B C & = \begin{bmatrix}
b_{11} & b_{12} & b_{13} & \cdots & b_{1,n-1}  & b_{1,n} \\
b_{21} & b_{22} & b_{23} & \cdots & b_{2,n-1} & 0 \\
b_{31} & b_{32} & b_{33} & \cdots & 0 & 0 \\
\vdots & \cdot^{\cdot^{\cdot}} & \vdots & \vdots & \vdots & \vdots \\
b_{n1} & 0 & 0 & \cdots & 0 & 0
\end{bmatrix}
\begin{bmatrix}
0 & 0& 0 & \cdots & 0  & c_{1,n} \\
0 & 0 & 0 & \cdots & c_{2,n-1} & c_{2,n} \\
0 & 0 & 0 & \cdot^{\cdot^{\cdot}} & c_{3,n-1} & c_{3,n} \\
\vdots & \vdots & \vdots & \vdots & \vdots & \vdots \\
c_{n1} & c_{n2} & c_{n3} & \cdots & c_{n,n-1} & c_{n,n}
\end{bmatrix} \\
& = \begin{bmatrix}
b_{1,n} c_{n,1} & * & * & \cdots & * \\
0 & b_{2,n-1} c_{n-1,2} & * & \cdots & * \\
0 & 0 & b_{3,n-2} c_{n-2,3} & \cdots & * \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
0 & 0 & 0 & \cdots & b_{n,1} c_{1,n}
\end{bmatrix}
\end{aligned}
$$



In [2]:
print("B:")
print(B)
print("\nC:")
print(C)
print("\nBC:")
print(np.dot(B,C))
print("\nCB:")
print(np.dot(C,B))

B:
[[5 7 6 4 5]
 [2 2 5 3 0]
 [3 1 1 0 0]
 [2 1 0 0 0]
 [9 0 0 0 0]]

C:
[[0 0 0 0 2]
 [0 0 0 6 6]
 [0 0 6 6 5]
 [0 5 1 7 6]
 [5 4 5 8 8]]

BC:
[[ 25  40  65 146 146]
 [  0  15  33  63  59]
 [  0   0   6  12  17]
 [  0   0   0   6  10]
 [  0   0   0   0  18]]

CB:
[[ 18   0   0   0   0]
 [ 66   6   0   0   0]
 [ 75  12   6   0   0]
 [ 81  18  26  15   0]
 [136  56  55  32  25]]


## transpose(B)

If $B$ is northwest then $B^T$ is also northwest.

In [3]:
print("B:")
print(B)
print("\ntranspose(B)")
print(B.T)

B:
[[5 7 6 4 5]
 [2 2 5 3 0]
 [3 1 1 0 0]
 [2 1 0 0 0]
 [9 0 0 0 0]]

transpose(B)
[[5 2 3 2 9]
 [7 2 1 1 0]
 [6 5 1 0 0]
 [4 3 0 0 0]
 [5 0 0 0 0]]


## Reference 
* Introduction to Linear algebra 5th edition (Prob36 in chapter 2.7)
* https://en.wikipedia.org/wiki/Persymmetric_matrix