## Perfect shuffle matrix

### Example

$$
S_{2,3} =
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 & 0 & 0 \\
0 & 1 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 1 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 1
\end{bmatrix} \in \mathbb{R}^{6 \times 6}
$$

$$
S_{2,4}=
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 1
\end{bmatrix} \in \mathbb{R}^{8 \times 8}
$$



In [1]:
import numpy as np

def perfect_shuffle_matrix(m1, m2):
    S = np.zeros(shape=(m1*m2, m1*m2))
    for k in range(m2):
        for i in range(m1):
            S[k*m1+i, i*m2+k] = 1
    return S

S23 = perfect_shuffle_matrix(2,3)
S24 = perfect_shuffle_matrix(2,4)

print("\nS23:")
print(S23)
print("\nS24:")
print(S24)


S23:
[[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]

S24:
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


## Shuffle rows and columns

In [2]:
import numpy as np

def perfect_shuffle_matrix(m1, m2):
    S = np.zeros(shape=(m1*m2, m1*m2))
    for k in range(m2):
        for i in range(m1):
            S[k*m1+i, i*m2+k] = 1
    return S


m1, m2 = 2, 4
A = np.array([[i*10+j for j in range(1, m1*m2+1)] for i in range(1, m1*m2+1)])
S = perfect_shuffle_matrix(m1, m2)

print("\nA:")
print(A)
print(f"\nS{m1},{m2}:")
print(S)
print("\nSA:")
print(S@A)
print("\nA@S.T:")
print(A@S.T)
print("\nS@A@S.T")
print(S@A@S.T)



A:
[[11 12 13 14 15 16 17 18]
 [21 22 23 24 25 26 27 28]
 [31 32 33 34 35 36 37 38]
 [41 42 43 44 45 46 47 48]
 [51 52 53 54 55 56 57 58]
 [61 62 63 64 65 66 67 68]
 [71 72 73 74 75 76 77 78]
 [81 82 83 84 85 86 87 88]]

S2,4:
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]

SA:
[[11. 12. 13. 14. 15. 16. 17. 18.]
 [51. 52. 53. 54. 55. 56. 57. 58.]
 [21. 22. 23. 24. 25. 26. 27. 28.]
 [61. 62. 63. 64. 65. 66. 67. 68.]
 [31. 32. 33. 34. 35. 36. 37. 38.]
 [71. 72. 73. 74. 75. 76. 77. 78.]
 [41. 42. 43. 44. 45. 46. 47. 48.]
 [81. 82. 83. 84. 85. 86. 87. 88.]]

A@S.T:
[[11. 15. 12. 16. 13. 17. 14. 18.]
 [21. 25. 22. 26. 23. 27. 24. 28.]
 [31. 35. 32. 36. 33. 37. 34. 38.]
 [41. 45. 42. 46. 43. 47. 44. 48.]
 [51. 55. 52. 56. 53. 57. 54. 58.]
 [61. 65. 62. 66. 63. 67. 64. 68.]
 [71. 75. 72. 76. 73. 77. 74. 78.]
 [81. 85. 82. 86

## Shuffle a block matrix

In [3]:
import numpy as np

m1, m2 = 2, 6
A = np.zeros(shape=(m1*m2, m1*m2))
S = perfect_shuffle_matrix(m1, m2)

B = np.zeros(shape=(m2,m2))
for i in range(m2):
    for j in range(m2):
        if i == j or i-j==-1:
            B[i, j] = (i+1)*10 +(j+1)
        

A[0:m2, m2:] = B
A[m2:, :m2] = B.T

print("\nA:")
print(A)
print("\nB:")
print(B)
print("\nS:")
print(S)
print("\nS@A@S.T")
print(S@A@S.T)




A:
[[ 0.  0.  0.  0.  0.  0. 11. 12.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 22. 23.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 33. 34.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. 44. 45.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 55. 56.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 66.]
 [11.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [12. 22.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 23. 33.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 34. 44.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 45. 55.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 56. 66.  0.  0.  0.  0.  0.  0.]]

B:
[[11. 12.  0.  0.  0.  0.]
 [ 0. 22. 23.  0.  0.  0.]
 [ 0.  0. 33. 34.  0.  0.]
 [ 0.  0.  0. 44. 45.  0.]
 [ 0.  0.  0.  0. 55. 56.]
 [ 0.  0.  0.  0.  0. 66.]]

S:
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 