# Permutation Matrix

## Row Based Permutation matrix

For example, for the permutation $\sigma = (2, 3, 4, 1)$, the corresponding row-based permutation matrix is:

$$
R_\sigma = 
\begin{pmatrix}
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1 \\
1 & 0 & 0 & 0
\end{pmatrix}
$$

## Product of two permutation matrices

$$
R_\sigma R_\tau = R_{\tau \circ \sigma}
$$

In [1]:
import numpy as np

# Row based Permutation matrix
def permutation_matrix(perm):
    n = len(perm)
    mat = np.zeros((n, n), dtype=int)
    for i, p in enumerate(perm):
        mat[i, p] = 1
    return mat

# Composite of two permutations
def composite_permutation(perm1, perm2):
    """
    Compute the composite of two permutations `perm1` and `perm2`.
    `perm1` is applied after `perm2`.
    """
    n = len(perm1)
    composite = [perm1[perm2[i]] for i in range(n)]
    return composite

# Generate Permutation matrices
sigma = [1, 2, 3, 0]
tau = [1, 0, 3, 2]
P1 = permutation_matrix(sigma)
P2 = permutation_matrix(tau)

# Generate a composite matrix
composite = composite_permutation(tau, sigma)
P3 = permutation_matrix(composite)

# product
product12 = np.dot(P1, P2)

# Display the results
print(f"Permutation Matrix P1(row-based) from sigma={sigma}:")
print(P1)
print(f"\nPermutation Matrix P2(row-based) from tau={tau}:")
print(P2)
print("\nP1 P2:")
print(product12)
print("\nPermutation Matrix P3 from composite permutation tau sigma:")
print(P3)

Permutation Matrix P1(row-based) from sigma=[1, 2, 3, 0]:
[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [1 0 0 0]]

Permutation Matrix P2(row-based) from tau=[1, 0, 3, 2]:
[[0 1 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]]

P1 P2:
[[1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]]

Permutation Matrix P3 from composite permutation tau sigma:
[[1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]]


## Inverse of permutation matrices

$$
P^{-1} = P^T
$$

In [2]:
import numpy as np

invP1 = np.linalg.inv(P1)
print("P1:")
print(P1)
print("\nTranspose(P1):")
print(P1.T)
print("\nInverse(P1) : ")
print(invP1)


P1:
[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [1 0 0 0]]

Transpose(P1):
[[0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]

Inverse(P1) : 
[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


## Determinant

$$
\text{det}(P) = \pm 1
$$

In [3]:
detP1 = np.linalg.det(P1)
detP2 = np.linalg.det(P2)
print("Dewterminant(P1):")
print(detP1)
print("Dewterminant(P2):")
print(detP2)

Dewterminant(P1):
-1.0
Dewterminant(P2):
1.0


## The order of a permutation matrix

$$
P^k = I, \quad k \leq n
$$

In [12]:
n = 4
num_examples = 3
for j in range(num_examples):
    random_perm = np.random.permutation(n)
    P = permutation_matrix(random_perm) 
    matrix_product = P
    
    # Find the orders of permutation matrices
    for i in range(n):
        matrix_product = np.dot(P, matrix_product)
        if (matrix_product == np.eye(n)).all():
            print("\nP:")
            print(P)
            print(f"\nOrder is {i+2}")
            break

    if not (matrix_product == np.eye(n)).all():
        print("Something strange")
        print("\nP:")
        print(P)
        print(f"P^{n}:")
        print(matrix_product)


P:
[[1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]]

Order is 2

P:
[[0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]

Order is 4

P:
[[0 1 0 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 0 1 0]]

Order is 4


## Permutating rows/columns of a matrix

$$
\begin{aligned}
R_\sigma A & = R_\sigma \begin{bmatrix} 
a_1^T \\
a_2^T \\
\vdots \\
a_n^T
\end{bmatrix} \\
& = \begin{bmatrix} 
a_{\sigma(1)}^T \\
a_{\sigma(2)}^T \\
\vdots \\
a_{\sigma(n)}^T
\end{bmatrix} \\
B C_\sigma & = \begin{bmatrix} b_1 & b_2 & \dots & b_n \end{bmatrix} C_\sigma  \\
& = \begin{bmatrix} b_{\sigma(1)} & b_{\sigma(2)} & \dots & b_{\sigma(n)} \end{bmatrix}
\end{aligned}
$$


In [5]:
A = np.array([[0,1,2],
             [3,4,5],
             [6,7,8]])
P = permutation_matrix([1,0,2])
row_exchanged_A = np.dot(P,A)
column_exchanged_A = np.dot(A,P)
print("\nP:")
print(P)
print("\nMatrix A:")
print(A)
print("\nP A:")
print(row_exchanged_A)
print("\nA P:")
print(column_exchanged_A)


P:
[[0 1 0]
 [1 0 0]
 [0 0 1]]

Matrix A:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

P A:
[[3 4 5]
 [0 1 2]
 [6 7 8]]

A P:
[[1 0 2]
 [4 3 5]
 [7 6 8]]


## Preserves inner Products
$$
(Px, Py) = (x,y)
$$

In [6]:
n = len(P1)
x = np.arange(1, n+1)
y = np.arange(n+1, 1, -1)
print("(P1 x, P1 y) = ", end="")
print(np.inner(P1@x, P1@y))
print("\n(x,y) = ", end="")
print(np.inner(x,y))

(P1 x, P1 y) = 30

(x,y) = 30
