## Persymmetric matrix
Let $(A)_{i,j} = a_{ij}$

A persymmetric matrix is a matrix that is symmetric with respect to anti-diagonal.

$$
A \text{ is a persymmetric matrix} \iff
a_{ij} = a_{n-j+1,\,n-i+1} \quad \forall i,j=1,\cdots,n
$$

https://en.wikipedia.org/wiki/Persymmetric_matrix

In [1]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 2],
    [6, 4, 1]
])

def is_persymmetric_matrix(A):
    """
    Check if a given matrix A is persymmetric (symmetric about the antidiagonal).
    """
    n = A.shape[0]
    if A.shape[0] != A.shape[1]:
        # Not a square matrix, so it can't be persymmetric
        return False
    
    # Check if A_{i,j} == A_{n-j-1, n-i-1} for all i, j
    for i in range(n):
        for j in range(n):
            if A[i, j] != A[n-j-1, n-i-1]:
                return False
    return True

if is_persymmetric_matrix(A):
    print("A is a persymmetric matrix (i.e., symmetric about the antidiagonal).")
else:
    print("A is not a persymmetric matrix.")

print("\nMatrix A:")
print(A)


A is a persymmetric matrix (i.e., symmetric about the antidiagonal).

Matrix A:
[[1 2 3]
 [4 5 2]
 [6 4 1]]


## transposing the matrix M about antidiagonal

In [2]:
import numpy as np

n = 5
A = np.array([[i*10+j for j in range(1,n+1)] for i in range(1, n+1)])

# exchange permutation E
E = np.fliplr(np.eye(n))

print("\nA:")
print(A)
print("\nE:")
print(E)
print("\nAntidiagonal transpose E@A^T@E:")
print(E@A.T@E)




A:
[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]
 [51 52 53 54 55]]

E:
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]

Antidiagonal transpose E@A^T@E:
[[55. 45. 35. 25. 15.]
 [54. 44. 34. 24. 14.]
 [53. 43. 33. 23. 13.]
 [52. 42. 32. 22. 12.]
 [51. 41. 31. 21. 11.]]


## Equivalent definition
Matrix A can be transposed about anti-diagonal  using the operation $E A^T E$, where E is the exchange permutation matrix.

Using this, we can derive an equivalent definition of a persymmetric matrix:

$$
A \text{ is a persymmetric matrix} \iff
A = E A^T E 
$$

- **Note**: this is an analogous to  the definition of a symmetric matrix $A = A^T$
