In [37]:
import numpy as np

In [38]:
X = np.array([[0, 4, 2],[5 ,0, 0], [5, 2, 0]])

In [39]:
indexes = X > 0

In [40]:
indexes

array([[False,  True,  True],
       [ True, False, False],
       [ True,  True, False]])

In [41]:
indexes[0]

array([False,  True,  True])

In [42]:
# choose positive values in X[0]
X[0, indexes[0]]

array([4, 2])

In [43]:
y = np.array([1, 1, 1])

In [44]:
y[indexes[0]]

array([1, 1])

In [45]:
X[0, indexes[0]] - y[indexes[0]]

array([3, 1])