In [90]:
import numpy as np

In [101]:
# flattened index(int) -> 2d array index(int, int)
np.unravel_index(3, (2,2)) # index=3 < 2*2=4

(1, 1)

In [115]:
# flattened index(int) -> 2d array index(int, int)
np.unravel_index(5, (3,3)) # index=5 < 3*3=9

(1, 2)

In [102]:
# flattened indices(=0,1,2,...,7) -> 3d array index([0th indices], [1st indices], [2nd indices] )
np.unravel_index([0,1,2,3,4,5,6,7], (2,2,2)) # each index < 2*2*2=8

(array([0, 0, 0, 0, 1, 1, 1, 1], dtype=int64),
 array([0, 0, 1, 1, 0, 0, 1, 1], dtype=int64),
 array([0, 1, 0, 1, 0, 1, 0, 1], dtype=int64))

In [127]:
# get the argmax(x[1,:,:]) in the 3d array shape
x = np.zeros((2,2,2))
x[1][1][1] = 10
x[0][1][0] = 10000000
x[1,:,:]

array([[ 0.,  0.],
       [ 0., 10.]])

In [128]:
np.argmax(x[1,:,:]) 

3

In [129]:
_, index1, index2 = np.unravel_index(np.argmax(x[1, ]), x.shape)
1, index1, index2

(1, 1, 1)